/**
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.api;

import org.openapitools.client.ApiInvoker;
import org.openapitools.client.ApiException;
import org.openapitools.client.Pair;

import org.openapitools.client.model.*;

import java.util.*;

import com.android.volley.Response;
import com.android.volley.VolleyError;

import org.openapitools.client.model.CPAASError;
import org.openapitools.client.model.ServiceAPIResponse;
import org.openapitools.client.model.ServiceDocsChannelGetAll;
import org.openapitools.client.model.ServiceDocsChannelGetSingle;
import org.openapitools.client.model.ServiceVOIPChannelRunActionData;
import org.openapitools.client.model.ServiceVOIPChannelRunMetaflowData;

import org.apache.http.HttpEntity;
import org.apache.http.entity.mime.MultipartEntityBuilder;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.TimeoutException;

public class ChannelApi {
  String basePath = "http://API_HOSTNAME";
  ApiInvoker apiInvoker = ApiInvoker.getInstance();

  public void addHeader(String key, String value) {
    getInvoker().addDefaultHeader(key, value);
  }

  public ApiInvoker getInvoker() {
    return apiInvoker;
  }

  public void setBasePath(String basePath) {
    this.basePath = basePath;
  }

  public String getBasePath() {
    return basePath;
  }

  /**
  * Get Channel Details
  * Access details about each channel in an account.
   * @param accountID Account ID, 32 alpha numeric
   * @param channelID Channel ID
   * @return ServiceDocsChannelGetSingle
  */
  public ServiceDocsChannelGetSingle v1AccountAccountIDChannelChannelIDGet (String accountID, String channelID) throws TimeoutException, ExecutionException, InterruptedException, ApiException {
    Object postBody = null;
    // verify the required parameter 'accountID' is set
    if (accountID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'accountID' when calling v1AccountAccountIDChannelChannelIDGet",
        new ApiException(400, "Missing the required parameter 'accountID' when calling v1AccountAccountIDChannelChannelIDGet"));
    }
    // verify the required parameter 'channelID' is set
    if (channelID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'channelID' when calling v1AccountAccountIDChannelChannelIDGet",
        new ApiException(400, "Missing the required parameter 'channelID' when calling v1AccountAccountIDChannelChannelIDGet"));
    }

    // create path and map variables
    String path = "/v1/account/{accountID}/channel/{channelID}".replaceAll("\\{" + "accountID" + "\\}", apiInvoker.escapeString(accountID.toString())).replaceAll("\\{" + "channelID" + "\\}", apiInvoker.escapeString(channelID.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();
    String[] contentTypes = {
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
    }

    String[] authNames = new String[] { "BearerAuth" };

    try {
      String localVarResponse = apiInvoker.invokeAPI (basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames);
      if (localVarResponse != null) {
         return (ServiceDocsChannelGetSingle) ApiInvoker.deserialize(localVarResponse, "", ServiceDocsChannelGetSingle.class);
      } else {
         return null;
      }
    } catch (ApiException ex) {
       throw ex;
    } catch (InterruptedException ex) {
       throw ex;
    } catch (ExecutionException ex) {
      if (ex.getCause() instanceof VolleyError) {
        VolleyError volleyError = (VolleyError)ex.getCause();
        if (volleyError.networkResponse != null) {
          throw new ApiException(volleyError.networkResponse.statusCode, volleyError.getMessage());
        }
      }
      throw ex;
    } catch (TimeoutException ex) {
      throw ex;
    }
  }

      /**
   * Get Channel Details
   * Access details about each channel in an account.
   * @param accountID Account ID, 32 alpha numeric   * @param channelID Channel ID
  */
  public void v1AccountAccountIDChannelChannelIDGet (String accountID, String channelID, final Response.Listener<ServiceDocsChannelGetSingle> responseListener, final Response.ErrorListener errorListener) {
    Object postBody = null;

    // verify the required parameter 'accountID' is set
    if (accountID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'accountID' when calling v1AccountAccountIDChannelChannelIDGet",
        new ApiException(400, "Missing the required parameter 'accountID' when calling v1AccountAccountIDChannelChannelIDGet"));
    }
    // verify the required parameter 'channelID' is set
    if (channelID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'channelID' when calling v1AccountAccountIDChannelChannelIDGet",
        new ApiException(400, "Missing the required parameter 'channelID' when calling v1AccountAccountIDChannelChannelIDGet"));
    }

    // create path and map variables
    String path = "/v1/account/{accountID}/channel/{channelID}".replaceAll("\\{format\\}","json").replaceAll("\\{" + "accountID" + "\\}", apiInvoker.escapeString(accountID.toString())).replaceAll("\\{" + "channelID" + "\\}", apiInvoker.escapeString(channelID.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();



    String[] contentTypes = {
      
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
          }

    String[] authNames = new String[] { "BearerAuth" };

    try {
      apiInvoker.invokeAPI(basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames,
        new Response.Listener<String>() {
          @Override
          public void onResponse(String localVarResponse) {
            try {
              responseListener.onResponse((ServiceDocsChannelGetSingle) ApiInvoker.deserialize(localVarResponse,  "", ServiceDocsChannelGetSingle.class));
            } catch (ApiException exception) {
               errorListener.onErrorResponse(new VolleyError(exception));
            }
          }
      }, new Response.ErrorListener() {
          @Override
          public void onErrorResponse(VolleyError error) {
            errorListener.onErrorResponse(error);
          }
      });
    } catch (ApiException ex) {
      errorListener.onErrorResponse(new VolleyError(ex));
    }
  }
  /**
  * Associate Action to Channel
  * Link an action, such as transfer or hangup to a channel.
   * @param accountID Account ID, 32 alpha numeric
   * @param channelID Channel ID
   * @param reqBody payload fields
   * @return ServiceAPIResponse
  */
  public ServiceAPIResponse v1AccountAccountIDChannelChannelIDPost (String accountID, String channelID, ServiceVOIPChannelRunActionData reqBody) throws TimeoutException, ExecutionException, InterruptedException, ApiException {
    Object postBody = reqBody;
    // verify the required parameter 'accountID' is set
    if (accountID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'accountID' when calling v1AccountAccountIDChannelChannelIDPost",
        new ApiException(400, "Missing the required parameter 'accountID' when calling v1AccountAccountIDChannelChannelIDPost"));
    }
    // verify the required parameter 'channelID' is set
    if (channelID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'channelID' when calling v1AccountAccountIDChannelChannelIDPost",
        new ApiException(400, "Missing the required parameter 'channelID' when calling v1AccountAccountIDChannelChannelIDPost"));
    }
    // verify the required parameter 'reqBody' is set
    if (reqBody == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'reqBody' when calling v1AccountAccountIDChannelChannelIDPost",
        new ApiException(400, "Missing the required parameter 'reqBody' when calling v1AccountAccountIDChannelChannelIDPost"));
    }

    // create path and map variables
    String path = "/v1/account/{accountID}/channel/{channelID}".replaceAll("\\{" + "accountID" + "\\}", apiInvoker.escapeString(accountID.toString())).replaceAll("\\{" + "channelID" + "\\}", apiInvoker.escapeString(channelID.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();
    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
    }

    String[] authNames = new String[] { "BearerAuth" };

    try {
      String localVarResponse = apiInvoker.invokeAPI (basePath, path, "POST", queryParams, postBody, headerParams, formParams, contentType, authNames);
      if (localVarResponse != null) {
         return (ServiceAPIResponse) ApiInvoker.deserialize(localVarResponse, "", ServiceAPIResponse.class);
      } else {
         return null;
      }
    } catch (ApiException ex) {
       throw ex;
    } catch (InterruptedException ex) {
       throw ex;
    } catch (ExecutionException ex) {
      if (ex.getCause() instanceof VolleyError) {
        VolleyError volleyError = (VolleyError)ex.getCause();
        if (volleyError.networkResponse != null) {
          throw new ApiException(volleyError.networkResponse.statusCode, volleyError.getMessage());
        }
      }
      throw ex;
    } catch (TimeoutException ex) {
      throw ex;
    }
  }

      /**
   * Associate Action to Channel
   * Link an action, such as transfer or hangup to a channel.
   * @param accountID Account ID, 32 alpha numeric   * @param channelID Channel ID   * @param reqBody payload fields
  */
  public void v1AccountAccountIDChannelChannelIDPost (String accountID, String channelID, ServiceVOIPChannelRunActionData reqBody, final Response.Listener<ServiceAPIResponse> responseListener, final Response.ErrorListener errorListener) {
    Object postBody = reqBody;

    // verify the required parameter 'accountID' is set
    if (accountID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'accountID' when calling v1AccountAccountIDChannelChannelIDPost",
        new ApiException(400, "Missing the required parameter 'accountID' when calling v1AccountAccountIDChannelChannelIDPost"));
    }
    // verify the required parameter 'channelID' is set
    if (channelID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'channelID' when calling v1AccountAccountIDChannelChannelIDPost",
        new ApiException(400, "Missing the required parameter 'channelID' when calling v1AccountAccountIDChannelChannelIDPost"));
    }
    // verify the required parameter 'reqBody' is set
    if (reqBody == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'reqBody' when calling v1AccountAccountIDChannelChannelIDPost",
        new ApiException(400, "Missing the required parameter 'reqBody' when calling v1AccountAccountIDChannelChannelIDPost"));
    }

    // create path and map variables
    String path = "/v1/account/{accountID}/channel/{channelID}".replaceAll("\\{format\\}","json").replaceAll("\\{" + "accountID" + "\\}", apiInvoker.escapeString(accountID.toString())).replaceAll("\\{" + "channelID" + "\\}", apiInvoker.escapeString(channelID.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();



    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
          }

    String[] authNames = new String[] { "BearerAuth" };

    try {
      apiInvoker.invokeAPI(basePath, path, "POST", queryParams, postBody, headerParams, formParams, contentType, authNames,
        new Response.Listener<String>() {
          @Override
          public void onResponse(String localVarResponse) {
            try {
              responseListener.onResponse((ServiceAPIResponse) ApiInvoker.deserialize(localVarResponse,  "", ServiceAPIResponse.class));
            } catch (ApiException exception) {
               errorListener.onErrorResponse(new VolleyError(exception));
            }
          }
      }, new Response.ErrorListener() {
          @Override
          public void onErrorResponse(VolleyError error) {
            errorListener.onErrorResponse(error);
          }
      });
    } catch (ApiException ex) {
      errorListener.onErrorResponse(new VolleyError(ex));
    }
  }
  /**
  * Associate Metaflow to Channel
  * Link a metaflow to an active channel.
   * @param accountID Account ID, 32 alpha numeric
   * @param channelID Channel ID
   * @param reqBody payload fields
   * @return ServiceAPIResponse
  */
  public ServiceAPIResponse v1AccountAccountIDChannelChannelIDPut (String accountID, String channelID, ServiceVOIPChannelRunMetaflowData reqBody) throws TimeoutException, ExecutionException, InterruptedException, ApiException {
    Object postBody = reqBody;
    // verify the required parameter 'accountID' is set
    if (accountID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'accountID' when calling v1AccountAccountIDChannelChannelIDPut",
        new ApiException(400, "Missing the required parameter 'accountID' when calling v1AccountAccountIDChannelChannelIDPut"));
    }
    // verify the required parameter 'channelID' is set
    if (channelID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'channelID' when calling v1AccountAccountIDChannelChannelIDPut",
        new ApiException(400, "Missing the required parameter 'channelID' when calling v1AccountAccountIDChannelChannelIDPut"));
    }
    // verify the required parameter 'reqBody' is set
    if (reqBody == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'reqBody' when calling v1AccountAccountIDChannelChannelIDPut",
        new ApiException(400, "Missing the required parameter 'reqBody' when calling v1AccountAccountIDChannelChannelIDPut"));
    }

    // create path and map variables
    String path = "/v1/account/{accountID}/channel/{channelID}".replaceAll("\\{" + "accountID" + "\\}", apiInvoker.escapeString(accountID.toString())).replaceAll("\\{" + "channelID" + "\\}", apiInvoker.escapeString(channelID.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();
    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
    }

    String[] authNames = new String[] { "BearerAuth" };

    try {
      String localVarResponse = apiInvoker.invokeAPI (basePath, path, "PUT", queryParams, postBody, headerParams, formParams, contentType, authNames);
      if (localVarResponse != null) {
         return (ServiceAPIResponse) ApiInvoker.deserialize(localVarResponse, "", ServiceAPIResponse.class);
      } else {
         return null;
      }
    } catch (ApiException ex) {
       throw ex;
    } catch (InterruptedException ex) {
       throw ex;
    } catch (ExecutionException ex) {
      if (ex.getCause() instanceof VolleyError) {
        VolleyError volleyError = (VolleyError)ex.getCause();
        if (volleyError.networkResponse != null) {
          throw new ApiException(volleyError.networkResponse.statusCode, volleyError.getMessage());
        }
      }
      throw ex;
    } catch (TimeoutException ex) {
      throw ex;
    }
  }

      /**
   * Associate Metaflow to Channel
   * Link a metaflow to an active channel.
   * @param accountID Account ID, 32 alpha numeric   * @param channelID Channel ID   * @param reqBody payload fields
  */
  public void v1AccountAccountIDChannelChannelIDPut (String accountID, String channelID, ServiceVOIPChannelRunMetaflowData reqBody, final Response.Listener<ServiceAPIResponse> responseListener, final Response.ErrorListener errorListener) {
    Object postBody = reqBody;

    // verify the required parameter 'accountID' is set
    if (accountID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'accountID' when calling v1AccountAccountIDChannelChannelIDPut",
        new ApiException(400, "Missing the required parameter 'accountID' when calling v1AccountAccountIDChannelChannelIDPut"));
    }
    // verify the required parameter 'channelID' is set
    if (channelID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'channelID' when calling v1AccountAccountIDChannelChannelIDPut",
        new ApiException(400, "Missing the required parameter 'channelID' when calling v1AccountAccountIDChannelChannelIDPut"));
    }
    // verify the required parameter 'reqBody' is set
    if (reqBody == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'reqBody' when calling v1AccountAccountIDChannelChannelIDPut",
        new ApiException(400, "Missing the required parameter 'reqBody' when calling v1AccountAccountIDChannelChannelIDPut"));
    }

    // create path and map variables
    String path = "/v1/account/{accountID}/channel/{channelID}".replaceAll("\\{format\\}","json").replaceAll("\\{" + "accountID" + "\\}", apiInvoker.escapeString(accountID.toString())).replaceAll("\\{" + "channelID" + "\\}", apiInvoker.escapeString(channelID.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();



    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
          }

    String[] authNames = new String[] { "BearerAuth" };

    try {
      apiInvoker.invokeAPI(basePath, path, "PUT", queryParams, postBody, headerParams, formParams, contentType, authNames,
        new Response.Listener<String>() {
          @Override
          public void onResponse(String localVarResponse) {
            try {
              responseListener.onResponse((ServiceAPIResponse) ApiInvoker.deserialize(localVarResponse,  "", ServiceAPIResponse.class));
            } catch (ApiException exception) {
               errorListener.onErrorResponse(new VolleyError(exception));
            }
          }
      }, new Response.ErrorListener() {
          @Override
          public void onErrorResponse(VolleyError error) {
            errorListener.onErrorResponse(error);
          }
      });
    } catch (ApiException ex) {
      errorListener.onErrorResponse(new VolleyError(ex));
    }
  }
  /**
  * Get Account Channel List
  * Get a list of active channels for an account.
   * @param accountID Account ID, 32 alpha numeric
   * @return ServiceDocsChannelGetAll
  */
  public ServiceDocsChannelGetAll v1AccountAccountIDChannelGet (String accountID) throws TimeoutException, ExecutionException, InterruptedException, ApiException {
    Object postBody = null;
    // verify the required parameter 'accountID' is set
    if (accountID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'accountID' when calling v1AccountAccountIDChannelGet",
        new ApiException(400, "Missing the required parameter 'accountID' when calling v1AccountAccountIDChannelGet"));
    }

    // create path and map variables
    String path = "/v1/account/{accountID}/channel".replaceAll("\\{" + "accountID" + "\\}", apiInvoker.escapeString(accountID.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();
    String[] contentTypes = {
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
    }

    String[] authNames = new String[] { "BearerAuth" };

    try {
      String localVarResponse = apiInvoker.invokeAPI (basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames);
      if (localVarResponse != null) {
         return (ServiceDocsChannelGetAll) ApiInvoker.deserialize(localVarResponse, "", ServiceDocsChannelGetAll.class);
      } else {
         return null;
      }
    } catch (ApiException ex) {
       throw ex;
    } catch (InterruptedException ex) {
       throw ex;
    } catch (ExecutionException ex) {
      if (ex.getCause() instanceof VolleyError) {
        VolleyError volleyError = (VolleyError)ex.getCause();
        if (volleyError.networkResponse != null) {
          throw new ApiException(volleyError.networkResponse.statusCode, volleyError.getMessage());
        }
      }
      throw ex;
    } catch (TimeoutException ex) {
      throw ex;
    }
  }

      /**
   * Get Account Channel List
   * Get a list of active channels for an account.
   * @param accountID Account ID, 32 alpha numeric
  */
  public void v1AccountAccountIDChannelGet (String accountID, final Response.Listener<ServiceDocsChannelGetAll> responseListener, final Response.ErrorListener errorListener) {
    Object postBody = null;

    // verify the required parameter 'accountID' is set
    if (accountID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'accountID' when calling v1AccountAccountIDChannelGet",
        new ApiException(400, "Missing the required parameter 'accountID' when calling v1AccountAccountIDChannelGet"));
    }

    // create path and map variables
    String path = "/v1/account/{accountID}/channel".replaceAll("\\{format\\}","json").replaceAll("\\{" + "accountID" + "\\}", apiInvoker.escapeString(accountID.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();



    String[] contentTypes = {
      
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
          }

    String[] authNames = new String[] { "BearerAuth" };

    try {
      apiInvoker.invokeAPI(basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames,
        new Response.Listener<String>() {
          @Override
          public void onResponse(String localVarResponse) {
            try {
              responseListener.onResponse((ServiceDocsChannelGetAll) ApiInvoker.deserialize(localVarResponse,  "", ServiceDocsChannelGetAll.class));
            } catch (ApiException exception) {
               errorListener.onErrorResponse(new VolleyError(exception));
            }
          }
      }, new Response.ErrorListener() {
          @Override
          public void onErrorResponse(VolleyError error) {
            errorListener.onErrorResponse(error);
          }
      });
    } catch (ApiException ex) {
      errorListener.onErrorResponse(new VolleyError(ex));
    }
  }
  /**
  * Get Device Channel List
  * Get the list of active channels for a device.
   * @param accountID Account ID, 32 alpha numeric
   * @param deviceID Device ID, 32 alpha numeric
   * @return ServiceDocsChannelGetAll
  */
  public ServiceDocsChannelGetAll v1AccountAccountIDDeviceDeviceIDChannelGet (String accountID, String deviceID) throws TimeoutException, ExecutionException, InterruptedException, ApiException {
    Object postBody = null;
    // verify the required parameter 'accountID' is set
    if (accountID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'accountID' when calling v1AccountAccountIDDeviceDeviceIDChannelGet",
        new ApiException(400, "Missing the required parameter 'accountID' when calling v1AccountAccountIDDeviceDeviceIDChannelGet"));
    }
    // verify the required parameter 'deviceID' is set
    if (deviceID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'deviceID' when calling v1AccountAccountIDDeviceDeviceIDChannelGet",
        new ApiException(400, "Missing the required parameter 'deviceID' when calling v1AccountAccountIDDeviceDeviceIDChannelGet"));
    }

    // create path and map variables
    String path = "/v1/account/{accountID}/device/{deviceID}/channel".replaceAll("\\{" + "accountID" + "\\}", apiInvoker.escapeString(accountID.toString())).replaceAll("\\{" + "deviceID" + "\\}", apiInvoker.escapeString(deviceID.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();
    String[] contentTypes = {
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
    }

    String[] authNames = new String[] { "BearerAuth" };

    try {
      String localVarResponse = apiInvoker.invokeAPI (basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames);
      if (localVarResponse != null) {
         return (ServiceDocsChannelGetAll) ApiInvoker.deserialize(localVarResponse, "", ServiceDocsChannelGetAll.class);
      } else {
         return null;
      }
    } catch (ApiException ex) {
       throw ex;
    } catch (InterruptedException ex) {
       throw ex;
    } catch (ExecutionException ex) {
      if (ex.getCause() instanceof VolleyError) {
        VolleyError volleyError = (VolleyError)ex.getCause();
        if (volleyError.networkResponse != null) {
          throw new ApiException(volleyError.networkResponse.statusCode, volleyError.getMessage());
        }
      }
      throw ex;
    } catch (TimeoutException ex) {
      throw ex;
    }
  }

      /**
   * Get Device Channel List
   * Get the list of active channels for a device.
   * @param accountID Account ID, 32 alpha numeric   * @param deviceID Device ID, 32 alpha numeric
  */
  public void v1AccountAccountIDDeviceDeviceIDChannelGet (String accountID, String deviceID, final Response.Listener<ServiceDocsChannelGetAll> responseListener, final Response.ErrorListener errorListener) {
    Object postBody = null;

    // verify the required parameter 'accountID' is set
    if (accountID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'accountID' when calling v1AccountAccountIDDeviceDeviceIDChannelGet",
        new ApiException(400, "Missing the required parameter 'accountID' when calling v1AccountAccountIDDeviceDeviceIDChannelGet"));
    }
    // verify the required parameter 'deviceID' is set
    if (deviceID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'deviceID' when calling v1AccountAccountIDDeviceDeviceIDChannelGet",
        new ApiException(400, "Missing the required parameter 'deviceID' when calling v1AccountAccountIDDeviceDeviceIDChannelGet"));
    }

    // create path and map variables
    String path = "/v1/account/{accountID}/device/{deviceID}/channel".replaceAll("\\{format\\}","json").replaceAll("\\{" + "accountID" + "\\}", apiInvoker.escapeString(accountID.toString())).replaceAll("\\{" + "deviceID" + "\\}", apiInvoker.escapeString(deviceID.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();



    String[] contentTypes = {
      
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
          }

    String[] authNames = new String[] { "BearerAuth" };

    try {
      apiInvoker.invokeAPI(basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames,
        new Response.Listener<String>() {
          @Override
          public void onResponse(String localVarResponse) {
            try {
              responseListener.onResponse((ServiceDocsChannelGetAll) ApiInvoker.deserialize(localVarResponse,  "", ServiceDocsChannelGetAll.class));
            } catch (ApiException exception) {
               errorListener.onErrorResponse(new VolleyError(exception));
            }
          }
      }, new Response.ErrorListener() {
          @Override
          public void onErrorResponse(VolleyError error) {
            errorListener.onErrorResponse(error);
          }
      });
    } catch (ApiException ex) {
      errorListener.onErrorResponse(new VolleyError(ex));
    }
  }
  /**
  * Get User Channel List
  * Get the list of active channels for a user.
   * @param accountID Account ID, 32 alpha numeric
   * @param userID User ID, 32 alpha numeric
   * @return ServiceDocsChannelGetAll
  */
  public ServiceDocsChannelGetAll v1AccountAccountIDUserUserIDChannelGet (String accountID, String userID) throws TimeoutException, ExecutionException, InterruptedException, ApiException {
    Object postBody = null;
    // verify the required parameter 'accountID' is set
    if (accountID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'accountID' when calling v1AccountAccountIDUserUserIDChannelGet",
        new ApiException(400, "Missing the required parameter 'accountID' when calling v1AccountAccountIDUserUserIDChannelGet"));
    }
    // verify the required parameter 'userID' is set
    if (userID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'userID' when calling v1AccountAccountIDUserUserIDChannelGet",
        new ApiException(400, "Missing the required parameter 'userID' when calling v1AccountAccountIDUserUserIDChannelGet"));
    }

    // create path and map variables
    String path = "/v1/account/{accountID}/user/{userID}/channel".replaceAll("\\{" + "accountID" + "\\}", apiInvoker.escapeString(accountID.toString())).replaceAll("\\{" + "userID" + "\\}", apiInvoker.escapeString(userID.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();
    String[] contentTypes = {
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
    }

    String[] authNames = new String[] { "BearerAuth" };

    try {
      String localVarResponse = apiInvoker.invokeAPI (basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames);
      if (localVarResponse != null) {
         return (ServiceDocsChannelGetAll) ApiInvoker.deserialize(localVarResponse, "", ServiceDocsChannelGetAll.class);
      } else {
         return null;
      }
    } catch (ApiException ex) {
       throw ex;
    } catch (InterruptedException ex) {
       throw ex;
    } catch (ExecutionException ex) {
      if (ex.getCause() instanceof VolleyError) {
        VolleyError volleyError = (VolleyError)ex.getCause();
        if (volleyError.networkResponse != null) {
          throw new ApiException(volleyError.networkResponse.statusCode, volleyError.getMessage());
        }
      }
      throw ex;
    } catch (TimeoutException ex) {
      throw ex;
    }
  }

      /**
   * Get User Channel List
   * Get the list of active channels for a user.
   * @param accountID Account ID, 32 alpha numeric   * @param userID User ID, 32 alpha numeric
  */
  public void v1AccountAccountIDUserUserIDChannelGet (String accountID, String userID, final Response.Listener<ServiceDocsChannelGetAll> responseListener, final Response.ErrorListener errorListener) {
    Object postBody = null;

    // verify the required parameter 'accountID' is set
    if (accountID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'accountID' when calling v1AccountAccountIDUserUserIDChannelGet",
        new ApiException(400, "Missing the required parameter 'accountID' when calling v1AccountAccountIDUserUserIDChannelGet"));
    }
    // verify the required parameter 'userID' is set
    if (userID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'userID' when calling v1AccountAccountIDUserUserIDChannelGet",
        new ApiException(400, "Missing the required parameter 'userID' when calling v1AccountAccountIDUserUserIDChannelGet"));
    }

    // create path and map variables
    String path = "/v1/account/{accountID}/user/{userID}/channel".replaceAll("\\{format\\}","json").replaceAll("\\{" + "accountID" + "\\}", apiInvoker.escapeString(accountID.toString())).replaceAll("\\{" + "userID" + "\\}", apiInvoker.escapeString(userID.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();



    String[] contentTypes = {
      
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
          }

    String[] authNames = new String[] { "BearerAuth" };

    try {
      apiInvoker.invokeAPI(basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames,
        new Response.Listener<String>() {
          @Override
          public void onResponse(String localVarResponse) {
            try {
              responseListener.onResponse((ServiceDocsChannelGetAll) ApiInvoker.deserialize(localVarResponse,  "", ServiceDocsChannelGetAll.class));
            } catch (ApiException exception) {
               errorListener.onErrorResponse(new VolleyError(exception));
            }
          }
      }, new Response.ErrorListener() {
          @Override
          public void onErrorResponse(VolleyError error) {
            errorListener.onErrorResponse(error);
          }
      });
    } catch (ApiException ex) {
      errorListener.onErrorResponse(new VolleyError(ex));
    }
  }
}
