/**
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.api;

import org.openapitools.client.ApiInvoker;
import org.openapitools.client.ApiException;
import org.openapitools.client.Pair;

import org.openapitools.client.model.*;

import java.util.*;

import com.android.volley.Response;
import com.android.volley.VolleyError;

import org.openapitools.client.model.CPAASError;
import org.openapitools.client.model.ServiceDocsMetaflowGet;
import org.openapitools.client.model.ServiceVOIPMetaflowAddData;

import org.apache.http.HttpEntity;
import org.apache.http.entity.mime.MultipartEntityBuilder;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.TimeoutException;

public class MetaflowApi {
  String basePath = "http://API_HOSTNAME";
  ApiInvoker apiInvoker = ApiInvoker.getInstance();

  public void addHeader(String key, String value) {
    getInvoker().addDefaultHeader(key, value);
  }

  public ApiInvoker getInvoker() {
    return apiInvoker;
  }

  public void setBasePath(String basePath) {
    this.basePath = basePath;
  }

  public String getBasePath() {
    return basePath;
  }

  /**
  * Delete Device Metaflow
  * Delete all metaflows associated with a device.
   * @param accountID Account ID, 32 alpha numeric
   * @param deviceID Device ID, 32 alpha numeric
   * @return ServiceDocsMetaflowGet
  */
  public ServiceDocsMetaflowGet v1AccountAccountIDDeviceDeviceIDMetaflowDelete (String accountID, String deviceID) throws TimeoutException, ExecutionException, InterruptedException, ApiException {
    Object postBody = null;
    // verify the required parameter 'accountID' is set
    if (accountID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'accountID' when calling v1AccountAccountIDDeviceDeviceIDMetaflowDelete",
        new ApiException(400, "Missing the required parameter 'accountID' when calling v1AccountAccountIDDeviceDeviceIDMetaflowDelete"));
    }
    // verify the required parameter 'deviceID' is set
    if (deviceID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'deviceID' when calling v1AccountAccountIDDeviceDeviceIDMetaflowDelete",
        new ApiException(400, "Missing the required parameter 'deviceID' when calling v1AccountAccountIDDeviceDeviceIDMetaflowDelete"));
    }

    // create path and map variables
    String path = "/v1/account/{accountID}/device/{deviceID}/metaflow".replaceAll("\\{" + "accountID" + "\\}", apiInvoker.escapeString(accountID.toString())).replaceAll("\\{" + "deviceID" + "\\}", apiInvoker.escapeString(deviceID.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();
    String[] contentTypes = {
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
    }

    String[] authNames = new String[] { "BearerAuth" };

    try {
      String localVarResponse = apiInvoker.invokeAPI (basePath, path, "DELETE", queryParams, postBody, headerParams, formParams, contentType, authNames);
      if (localVarResponse != null) {
         return (ServiceDocsMetaflowGet) ApiInvoker.deserialize(localVarResponse, "", ServiceDocsMetaflowGet.class);
      } else {
         return null;
      }
    } catch (ApiException ex) {
       throw ex;
    } catch (InterruptedException ex) {
       throw ex;
    } catch (ExecutionException ex) {
      if (ex.getCause() instanceof VolleyError) {
        VolleyError volleyError = (VolleyError)ex.getCause();
        if (volleyError.networkResponse != null) {
          throw new ApiException(volleyError.networkResponse.statusCode, volleyError.getMessage());
        }
      }
      throw ex;
    } catch (TimeoutException ex) {
      throw ex;
    }
  }

      /**
   * Delete Device Metaflow
   * Delete all metaflows associated with a device.
   * @param accountID Account ID, 32 alpha numeric   * @param deviceID Device ID, 32 alpha numeric
  */
  public void v1AccountAccountIDDeviceDeviceIDMetaflowDelete (String accountID, String deviceID, final Response.Listener<ServiceDocsMetaflowGet> responseListener, final Response.ErrorListener errorListener) {
    Object postBody = null;

    // verify the required parameter 'accountID' is set
    if (accountID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'accountID' when calling v1AccountAccountIDDeviceDeviceIDMetaflowDelete",
        new ApiException(400, "Missing the required parameter 'accountID' when calling v1AccountAccountIDDeviceDeviceIDMetaflowDelete"));
    }
    // verify the required parameter 'deviceID' is set
    if (deviceID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'deviceID' when calling v1AccountAccountIDDeviceDeviceIDMetaflowDelete",
        new ApiException(400, "Missing the required parameter 'deviceID' when calling v1AccountAccountIDDeviceDeviceIDMetaflowDelete"));
    }

    // create path and map variables
    String path = "/v1/account/{accountID}/device/{deviceID}/metaflow".replaceAll("\\{format\\}","json").replaceAll("\\{" + "accountID" + "\\}", apiInvoker.escapeString(accountID.toString())).replaceAll("\\{" + "deviceID" + "\\}", apiInvoker.escapeString(deviceID.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();



    String[] contentTypes = {
      
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
          }

    String[] authNames = new String[] { "BearerAuth" };

    try {
      apiInvoker.invokeAPI(basePath, path, "DELETE", queryParams, postBody, headerParams, formParams, contentType, authNames,
        new Response.Listener<String>() {
          @Override
          public void onResponse(String localVarResponse) {
            try {
              responseListener.onResponse((ServiceDocsMetaflowGet) ApiInvoker.deserialize(localVarResponse,  "", ServiceDocsMetaflowGet.class));
            } catch (ApiException exception) {
               errorListener.onErrorResponse(new VolleyError(exception));
            }
          }
      }, new Response.ErrorListener() {
          @Override
          public void onErrorResponse(VolleyError error) {
            errorListener.onErrorResponse(error);
          }
      });
    } catch (ApiException ex) {
      errorListener.onErrorResponse(new VolleyError(ex));
    }
  }
  /**
  * Get Device Metaflow List
  * Get the list of metaflows for a device.
   * @param accountID Account ID, 32 alpha numeric
   * @param deviceID Device ID, 32 alpha numeric
   * @return ServiceDocsMetaflowGet
  */
  public ServiceDocsMetaflowGet v1AccountAccountIDDeviceDeviceIDMetaflowGet (String accountID, String deviceID) throws TimeoutException, ExecutionException, InterruptedException, ApiException {
    Object postBody = null;
    // verify the required parameter 'accountID' is set
    if (accountID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'accountID' when calling v1AccountAccountIDDeviceDeviceIDMetaflowGet",
        new ApiException(400, "Missing the required parameter 'accountID' when calling v1AccountAccountIDDeviceDeviceIDMetaflowGet"));
    }
    // verify the required parameter 'deviceID' is set
    if (deviceID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'deviceID' when calling v1AccountAccountIDDeviceDeviceIDMetaflowGet",
        new ApiException(400, "Missing the required parameter 'deviceID' when calling v1AccountAccountIDDeviceDeviceIDMetaflowGet"));
    }

    // create path and map variables
    String path = "/v1/account/{accountID}/device/{deviceID}/metaflow".replaceAll("\\{" + "accountID" + "\\}", apiInvoker.escapeString(accountID.toString())).replaceAll("\\{" + "deviceID" + "\\}", apiInvoker.escapeString(deviceID.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();
    String[] contentTypes = {
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
    }

    String[] authNames = new String[] { "BearerAuth" };

    try {
      String localVarResponse = apiInvoker.invokeAPI (basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames);
      if (localVarResponse != null) {
         return (ServiceDocsMetaflowGet) ApiInvoker.deserialize(localVarResponse, "", ServiceDocsMetaflowGet.class);
      } else {
         return null;
      }
    } catch (ApiException ex) {
       throw ex;
    } catch (InterruptedException ex) {
       throw ex;
    } catch (ExecutionException ex) {
      if (ex.getCause() instanceof VolleyError) {
        VolleyError volleyError = (VolleyError)ex.getCause();
        if (volleyError.networkResponse != null) {
          throw new ApiException(volleyError.networkResponse.statusCode, volleyError.getMessage());
        }
      }
      throw ex;
    } catch (TimeoutException ex) {
      throw ex;
    }
  }

      /**
   * Get Device Metaflow List
   * Get the list of metaflows for a device.
   * @param accountID Account ID, 32 alpha numeric   * @param deviceID Device ID, 32 alpha numeric
  */
  public void v1AccountAccountIDDeviceDeviceIDMetaflowGet (String accountID, String deviceID, final Response.Listener<ServiceDocsMetaflowGet> responseListener, final Response.ErrorListener errorListener) {
    Object postBody = null;

    // verify the required parameter 'accountID' is set
    if (accountID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'accountID' when calling v1AccountAccountIDDeviceDeviceIDMetaflowGet",
        new ApiException(400, "Missing the required parameter 'accountID' when calling v1AccountAccountIDDeviceDeviceIDMetaflowGet"));
    }
    // verify the required parameter 'deviceID' is set
    if (deviceID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'deviceID' when calling v1AccountAccountIDDeviceDeviceIDMetaflowGet",
        new ApiException(400, "Missing the required parameter 'deviceID' when calling v1AccountAccountIDDeviceDeviceIDMetaflowGet"));
    }

    // create path and map variables
    String path = "/v1/account/{accountID}/device/{deviceID}/metaflow".replaceAll("\\{format\\}","json").replaceAll("\\{" + "accountID" + "\\}", apiInvoker.escapeString(accountID.toString())).replaceAll("\\{" + "deviceID" + "\\}", apiInvoker.escapeString(deviceID.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();



    String[] contentTypes = {
      
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
          }

    String[] authNames = new String[] { "BearerAuth" };

    try {
      apiInvoker.invokeAPI(basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames,
        new Response.Listener<String>() {
          @Override
          public void onResponse(String localVarResponse) {
            try {
              responseListener.onResponse((ServiceDocsMetaflowGet) ApiInvoker.deserialize(localVarResponse,  "", ServiceDocsMetaflowGet.class));
            } catch (ApiException exception) {
               errorListener.onErrorResponse(new VolleyError(exception));
            }
          }
      }, new Response.ErrorListener() {
          @Override
          public void onErrorResponse(VolleyError error) {
            errorListener.onErrorResponse(error);
          }
      });
    } catch (ApiException ex) {
      errorListener.onErrorResponse(new VolleyError(ex));
    }
  }
  /**
  * Create Device Metaflow
  * Create a metaflow or multiple metaflows for a device.
   * @param accountID Account ID, 32 alpha numeric
   * @param deviceID Device ID, 32 alpha numeric
   * @param reqBody payload fields
   * @return ServiceDocsMetaflowGet
  */
  public ServiceDocsMetaflowGet v1AccountAccountIDDeviceDeviceIDMetaflowPost (String accountID, String deviceID, ServiceVOIPMetaflowAddData reqBody) throws TimeoutException, ExecutionException, InterruptedException, ApiException {
    Object postBody = reqBody;
    // verify the required parameter 'accountID' is set
    if (accountID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'accountID' when calling v1AccountAccountIDDeviceDeviceIDMetaflowPost",
        new ApiException(400, "Missing the required parameter 'accountID' when calling v1AccountAccountIDDeviceDeviceIDMetaflowPost"));
    }
    // verify the required parameter 'deviceID' is set
    if (deviceID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'deviceID' when calling v1AccountAccountIDDeviceDeviceIDMetaflowPost",
        new ApiException(400, "Missing the required parameter 'deviceID' when calling v1AccountAccountIDDeviceDeviceIDMetaflowPost"));
    }
    // verify the required parameter 'reqBody' is set
    if (reqBody == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'reqBody' when calling v1AccountAccountIDDeviceDeviceIDMetaflowPost",
        new ApiException(400, "Missing the required parameter 'reqBody' when calling v1AccountAccountIDDeviceDeviceIDMetaflowPost"));
    }

    // create path and map variables
    String path = "/v1/account/{accountID}/device/{deviceID}/metaflow".replaceAll("\\{" + "accountID" + "\\}", apiInvoker.escapeString(accountID.toString())).replaceAll("\\{" + "deviceID" + "\\}", apiInvoker.escapeString(deviceID.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();
    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
    }

    String[] authNames = new String[] { "BearerAuth" };

    try {
      String localVarResponse = apiInvoker.invokeAPI (basePath, path, "POST", queryParams, postBody, headerParams, formParams, contentType, authNames);
      if (localVarResponse != null) {
         return (ServiceDocsMetaflowGet) ApiInvoker.deserialize(localVarResponse, "", ServiceDocsMetaflowGet.class);
      } else {
         return null;
      }
    } catch (ApiException ex) {
       throw ex;
    } catch (InterruptedException ex) {
       throw ex;
    } catch (ExecutionException ex) {
      if (ex.getCause() instanceof VolleyError) {
        VolleyError volleyError = (VolleyError)ex.getCause();
        if (volleyError.networkResponse != null) {
          throw new ApiException(volleyError.networkResponse.statusCode, volleyError.getMessage());
        }
      }
      throw ex;
    } catch (TimeoutException ex) {
      throw ex;
    }
  }

      /**
   * Create Device Metaflow
   * Create a metaflow or multiple metaflows for a device.
   * @param accountID Account ID, 32 alpha numeric   * @param deviceID Device ID, 32 alpha numeric   * @param reqBody payload fields
  */
  public void v1AccountAccountIDDeviceDeviceIDMetaflowPost (String accountID, String deviceID, ServiceVOIPMetaflowAddData reqBody, final Response.Listener<ServiceDocsMetaflowGet> responseListener, final Response.ErrorListener errorListener) {
    Object postBody = reqBody;

    // verify the required parameter 'accountID' is set
    if (accountID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'accountID' when calling v1AccountAccountIDDeviceDeviceIDMetaflowPost",
        new ApiException(400, "Missing the required parameter 'accountID' when calling v1AccountAccountIDDeviceDeviceIDMetaflowPost"));
    }
    // verify the required parameter 'deviceID' is set
    if (deviceID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'deviceID' when calling v1AccountAccountIDDeviceDeviceIDMetaflowPost",
        new ApiException(400, "Missing the required parameter 'deviceID' when calling v1AccountAccountIDDeviceDeviceIDMetaflowPost"));
    }
    // verify the required parameter 'reqBody' is set
    if (reqBody == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'reqBody' when calling v1AccountAccountIDDeviceDeviceIDMetaflowPost",
        new ApiException(400, "Missing the required parameter 'reqBody' when calling v1AccountAccountIDDeviceDeviceIDMetaflowPost"));
    }

    // create path and map variables
    String path = "/v1/account/{accountID}/device/{deviceID}/metaflow".replaceAll("\\{format\\}","json").replaceAll("\\{" + "accountID" + "\\}", apiInvoker.escapeString(accountID.toString())).replaceAll("\\{" + "deviceID" + "\\}", apiInvoker.escapeString(deviceID.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();



    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
          }

    String[] authNames = new String[] { "BearerAuth" };

    try {
      apiInvoker.invokeAPI(basePath, path, "POST", queryParams, postBody, headerParams, formParams, contentType, authNames,
        new Response.Listener<String>() {
          @Override
          public void onResponse(String localVarResponse) {
            try {
              responseListener.onResponse((ServiceDocsMetaflowGet) ApiInvoker.deserialize(localVarResponse,  "", ServiceDocsMetaflowGet.class));
            } catch (ApiException exception) {
               errorListener.onErrorResponse(new VolleyError(exception));
            }
          }
      }, new Response.ErrorListener() {
          @Override
          public void onErrorResponse(VolleyError error) {
            errorListener.onErrorResponse(error);
          }
      });
    } catch (ApiException ex) {
      errorListener.onErrorResponse(new VolleyError(ex));
    }
  }
  /**
  * Delete Account Metaflow
  * Remove all metaflows from an account.
   * @param accountID Account ID, 32 alpha numeric
   * @return ServiceDocsMetaflowGet
  */
  public ServiceDocsMetaflowGet v1AccountAccountIDMetaflowDelete (String accountID) throws TimeoutException, ExecutionException, InterruptedException, ApiException {
    Object postBody = null;
    // verify the required parameter 'accountID' is set
    if (accountID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'accountID' when calling v1AccountAccountIDMetaflowDelete",
        new ApiException(400, "Missing the required parameter 'accountID' when calling v1AccountAccountIDMetaflowDelete"));
    }

    // create path and map variables
    String path = "/v1/account/{accountID}/metaflow".replaceAll("\\{" + "accountID" + "\\}", apiInvoker.escapeString(accountID.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();
    String[] contentTypes = {
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
    }

    String[] authNames = new String[] { "BearerAuth" };

    try {
      String localVarResponse = apiInvoker.invokeAPI (basePath, path, "DELETE", queryParams, postBody, headerParams, formParams, contentType, authNames);
      if (localVarResponse != null) {
         return (ServiceDocsMetaflowGet) ApiInvoker.deserialize(localVarResponse, "", ServiceDocsMetaflowGet.class);
      } else {
         return null;
      }
    } catch (ApiException ex) {
       throw ex;
    } catch (InterruptedException ex) {
       throw ex;
    } catch (ExecutionException ex) {
      if (ex.getCause() instanceof VolleyError) {
        VolleyError volleyError = (VolleyError)ex.getCause();
        if (volleyError.networkResponse != null) {
          throw new ApiException(volleyError.networkResponse.statusCode, volleyError.getMessage());
        }
      }
      throw ex;
    } catch (TimeoutException ex) {
      throw ex;
    }
  }

      /**
   * Delete Account Metaflow
   * Remove all metaflows from an account.
   * @param accountID Account ID, 32 alpha numeric
  */
  public void v1AccountAccountIDMetaflowDelete (String accountID, final Response.Listener<ServiceDocsMetaflowGet> responseListener, final Response.ErrorListener errorListener) {
    Object postBody = null;

    // verify the required parameter 'accountID' is set
    if (accountID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'accountID' when calling v1AccountAccountIDMetaflowDelete",
        new ApiException(400, "Missing the required parameter 'accountID' when calling v1AccountAccountIDMetaflowDelete"));
    }

    // create path and map variables
    String path = "/v1/account/{accountID}/metaflow".replaceAll("\\{format\\}","json").replaceAll("\\{" + "accountID" + "\\}", apiInvoker.escapeString(accountID.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();



    String[] contentTypes = {
      
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
          }

    String[] authNames = new String[] { "BearerAuth" };

    try {
      apiInvoker.invokeAPI(basePath, path, "DELETE", queryParams, postBody, headerParams, formParams, contentType, authNames,
        new Response.Listener<String>() {
          @Override
          public void onResponse(String localVarResponse) {
            try {
              responseListener.onResponse((ServiceDocsMetaflowGet) ApiInvoker.deserialize(localVarResponse,  "", ServiceDocsMetaflowGet.class));
            } catch (ApiException exception) {
               errorListener.onErrorResponse(new VolleyError(exception));
            }
          }
      }, new Response.ErrorListener() {
          @Override
          public void onErrorResponse(VolleyError error) {
            errorListener.onErrorResponse(error);
          }
      });
    } catch (ApiException ex) {
      errorListener.onErrorResponse(new VolleyError(ex));
    }
  }
  /**
  * Get Account Metaflow List
  * Get an account&#39;s metaflow list.
   * @param accountID Account ID, 32 alpha numeric
   * @return ServiceDocsMetaflowGet
  */
  public ServiceDocsMetaflowGet v1AccountAccountIDMetaflowGet (String accountID) throws TimeoutException, ExecutionException, InterruptedException, ApiException {
    Object postBody = null;
    // verify the required parameter 'accountID' is set
    if (accountID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'accountID' when calling v1AccountAccountIDMetaflowGet",
        new ApiException(400, "Missing the required parameter 'accountID' when calling v1AccountAccountIDMetaflowGet"));
    }

    // create path and map variables
    String path = "/v1/account/{accountID}/metaflow".replaceAll("\\{" + "accountID" + "\\}", apiInvoker.escapeString(accountID.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();
    String[] contentTypes = {
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
    }

    String[] authNames = new String[] { "BearerAuth" };

    try {
      String localVarResponse = apiInvoker.invokeAPI (basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames);
      if (localVarResponse != null) {
         return (ServiceDocsMetaflowGet) ApiInvoker.deserialize(localVarResponse, "", ServiceDocsMetaflowGet.class);
      } else {
         return null;
      }
    } catch (ApiException ex) {
       throw ex;
    } catch (InterruptedException ex) {
       throw ex;
    } catch (ExecutionException ex) {
      if (ex.getCause() instanceof VolleyError) {
        VolleyError volleyError = (VolleyError)ex.getCause();
        if (volleyError.networkResponse != null) {
          throw new ApiException(volleyError.networkResponse.statusCode, volleyError.getMessage());
        }
      }
      throw ex;
    } catch (TimeoutException ex) {
      throw ex;
    }
  }

      /**
   * Get Account Metaflow List
   * Get an account&#39;s metaflow list.
   * @param accountID Account ID, 32 alpha numeric
  */
  public void v1AccountAccountIDMetaflowGet (String accountID, final Response.Listener<ServiceDocsMetaflowGet> responseListener, final Response.ErrorListener errorListener) {
    Object postBody = null;

    // verify the required parameter 'accountID' is set
    if (accountID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'accountID' when calling v1AccountAccountIDMetaflowGet",
        new ApiException(400, "Missing the required parameter 'accountID' when calling v1AccountAccountIDMetaflowGet"));
    }

    // create path and map variables
    String path = "/v1/account/{accountID}/metaflow".replaceAll("\\{format\\}","json").replaceAll("\\{" + "accountID" + "\\}", apiInvoker.escapeString(accountID.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();



    String[] contentTypes = {
      
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
          }

    String[] authNames = new String[] { "BearerAuth" };

    try {
      apiInvoker.invokeAPI(basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames,
        new Response.Listener<String>() {
          @Override
          public void onResponse(String localVarResponse) {
            try {
              responseListener.onResponse((ServiceDocsMetaflowGet) ApiInvoker.deserialize(localVarResponse,  "", ServiceDocsMetaflowGet.class));
            } catch (ApiException exception) {
               errorListener.onErrorResponse(new VolleyError(exception));
            }
          }
      }, new Response.ErrorListener() {
          @Override
          public void onErrorResponse(VolleyError error) {
            errorListener.onErrorResponse(error);
          }
      });
    } catch (ApiException ex) {
      errorListener.onErrorResponse(new VolleyError(ex));
    }
  }
  /**
  * Create Account Metaflow
  * Generate a metaflow for an account.
   * @param accountID Account ID
   * @param metaflow Metaflow fields
   * @return ServiceDocsMetaflowGet
  */
  public ServiceDocsMetaflowGet v1AccountAccountIDMetaflowPost (String accountID, ServiceVOIPMetaflowAddData metaflow) throws TimeoutException, ExecutionException, InterruptedException, ApiException {
    Object postBody = metaflow;
    // verify the required parameter 'accountID' is set
    if (accountID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'accountID' when calling v1AccountAccountIDMetaflowPost",
        new ApiException(400, "Missing the required parameter 'accountID' when calling v1AccountAccountIDMetaflowPost"));
    }
    // verify the required parameter 'metaflow' is set
    if (metaflow == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'metaflow' when calling v1AccountAccountIDMetaflowPost",
        new ApiException(400, "Missing the required parameter 'metaflow' when calling v1AccountAccountIDMetaflowPost"));
    }

    // create path and map variables
    String path = "/v1/account/{accountID}/metaflow".replaceAll("\\{" + "accountID" + "\\}", apiInvoker.escapeString(accountID.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();
    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
    }

    String[] authNames = new String[] { "BearerAuth" };

    try {
      String localVarResponse = apiInvoker.invokeAPI (basePath, path, "POST", queryParams, postBody, headerParams, formParams, contentType, authNames);
      if (localVarResponse != null) {
         return (ServiceDocsMetaflowGet) ApiInvoker.deserialize(localVarResponse, "", ServiceDocsMetaflowGet.class);
      } else {
         return null;
      }
    } catch (ApiException ex) {
       throw ex;
    } catch (InterruptedException ex) {
       throw ex;
    } catch (ExecutionException ex) {
      if (ex.getCause() instanceof VolleyError) {
        VolleyError volleyError = (VolleyError)ex.getCause();
        if (volleyError.networkResponse != null) {
          throw new ApiException(volleyError.networkResponse.statusCode, volleyError.getMessage());
        }
      }
      throw ex;
    } catch (TimeoutException ex) {
      throw ex;
    }
  }

      /**
   * Create Account Metaflow
   * Generate a metaflow for an account.
   * @param accountID Account ID   * @param metaflow Metaflow fields
  */
  public void v1AccountAccountIDMetaflowPost (String accountID, ServiceVOIPMetaflowAddData metaflow, final Response.Listener<ServiceDocsMetaflowGet> responseListener, final Response.ErrorListener errorListener) {
    Object postBody = metaflow;

    // verify the required parameter 'accountID' is set
    if (accountID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'accountID' when calling v1AccountAccountIDMetaflowPost",
        new ApiException(400, "Missing the required parameter 'accountID' when calling v1AccountAccountIDMetaflowPost"));
    }
    // verify the required parameter 'metaflow' is set
    if (metaflow == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'metaflow' when calling v1AccountAccountIDMetaflowPost",
        new ApiException(400, "Missing the required parameter 'metaflow' when calling v1AccountAccountIDMetaflowPost"));
    }

    // create path and map variables
    String path = "/v1/account/{accountID}/metaflow".replaceAll("\\{format\\}","json").replaceAll("\\{" + "accountID" + "\\}", apiInvoker.escapeString(accountID.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();



    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
          }

    String[] authNames = new String[] { "BearerAuth" };

    try {
      apiInvoker.invokeAPI(basePath, path, "POST", queryParams, postBody, headerParams, formParams, contentType, authNames,
        new Response.Listener<String>() {
          @Override
          public void onResponse(String localVarResponse) {
            try {
              responseListener.onResponse((ServiceDocsMetaflowGet) ApiInvoker.deserialize(localVarResponse,  "", ServiceDocsMetaflowGet.class));
            } catch (ApiException exception) {
               errorListener.onErrorResponse(new VolleyError(exception));
            }
          }
      }, new Response.ErrorListener() {
          @Override
          public void onErrorResponse(VolleyError error) {
            errorListener.onErrorResponse(error);
          }
      });
    } catch (ApiException ex) {
      errorListener.onErrorResponse(new VolleyError(ex));
    }
  }
  /**
  * Delete User Metaflow
  * Delete all metaflows associated with a user.
   * @param accountID Account ID, 32 alpha numeric
   * @param userID user ID, 32 alpha numeric
   * @return ServiceDocsMetaflowGet
  */
  public ServiceDocsMetaflowGet v1AccountAccountIDUserUserIDMetaflowDelete (String accountID, String userID) throws TimeoutException, ExecutionException, InterruptedException, ApiException {
    Object postBody = null;
    // verify the required parameter 'accountID' is set
    if (accountID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'accountID' when calling v1AccountAccountIDUserUserIDMetaflowDelete",
        new ApiException(400, "Missing the required parameter 'accountID' when calling v1AccountAccountIDUserUserIDMetaflowDelete"));
    }
    // verify the required parameter 'userID' is set
    if (userID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'userID' when calling v1AccountAccountIDUserUserIDMetaflowDelete",
        new ApiException(400, "Missing the required parameter 'userID' when calling v1AccountAccountIDUserUserIDMetaflowDelete"));
    }

    // create path and map variables
    String path = "/v1/account/{accountID}/user/{userID}/metaflow".replaceAll("\\{" + "accountID" + "\\}", apiInvoker.escapeString(accountID.toString())).replaceAll("\\{" + "userID" + "\\}", apiInvoker.escapeString(userID.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();
    String[] contentTypes = {
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
    }

    String[] authNames = new String[] { "BearerAuth" };

    try {
      String localVarResponse = apiInvoker.invokeAPI (basePath, path, "DELETE", queryParams, postBody, headerParams, formParams, contentType, authNames);
      if (localVarResponse != null) {
         return (ServiceDocsMetaflowGet) ApiInvoker.deserialize(localVarResponse, "", ServiceDocsMetaflowGet.class);
      } else {
         return null;
      }
    } catch (ApiException ex) {
       throw ex;
    } catch (InterruptedException ex) {
       throw ex;
    } catch (ExecutionException ex) {
      if (ex.getCause() instanceof VolleyError) {
        VolleyError volleyError = (VolleyError)ex.getCause();
        if (volleyError.networkResponse != null) {
          throw new ApiException(volleyError.networkResponse.statusCode, volleyError.getMessage());
        }
      }
      throw ex;
    } catch (TimeoutException ex) {
      throw ex;
    }
  }

      /**
   * Delete User Metaflow
   * Delete all metaflows associated with a user.
   * @param accountID Account ID, 32 alpha numeric   * @param userID user ID, 32 alpha numeric
  */
  public void v1AccountAccountIDUserUserIDMetaflowDelete (String accountID, String userID, final Response.Listener<ServiceDocsMetaflowGet> responseListener, final Response.ErrorListener errorListener) {
    Object postBody = null;

    // verify the required parameter 'accountID' is set
    if (accountID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'accountID' when calling v1AccountAccountIDUserUserIDMetaflowDelete",
        new ApiException(400, "Missing the required parameter 'accountID' when calling v1AccountAccountIDUserUserIDMetaflowDelete"));
    }
    // verify the required parameter 'userID' is set
    if (userID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'userID' when calling v1AccountAccountIDUserUserIDMetaflowDelete",
        new ApiException(400, "Missing the required parameter 'userID' when calling v1AccountAccountIDUserUserIDMetaflowDelete"));
    }

    // create path and map variables
    String path = "/v1/account/{accountID}/user/{userID}/metaflow".replaceAll("\\{format\\}","json").replaceAll("\\{" + "accountID" + "\\}", apiInvoker.escapeString(accountID.toString())).replaceAll("\\{" + "userID" + "\\}", apiInvoker.escapeString(userID.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();



    String[] contentTypes = {
      
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
          }

    String[] authNames = new String[] { "BearerAuth" };

    try {
      apiInvoker.invokeAPI(basePath, path, "DELETE", queryParams, postBody, headerParams, formParams, contentType, authNames,
        new Response.Listener<String>() {
          @Override
          public void onResponse(String localVarResponse) {
            try {
              responseListener.onResponse((ServiceDocsMetaflowGet) ApiInvoker.deserialize(localVarResponse,  "", ServiceDocsMetaflowGet.class));
            } catch (ApiException exception) {
               errorListener.onErrorResponse(new VolleyError(exception));
            }
          }
      }, new Response.ErrorListener() {
          @Override
          public void onErrorResponse(VolleyError error) {
            errorListener.onErrorResponse(error);
          }
      });
    } catch (ApiException ex) {
      errorListener.onErrorResponse(new VolleyError(ex));
    }
  }
  /**
  * Get User Metaflow List
  * Get the list of metaflows for a user.
   * @param accountID Account ID, 32 alpha numeric
   * @param userID user ID, 32 alpha numeric
   * @return ServiceDocsMetaflowGet
  */
  public ServiceDocsMetaflowGet v1AccountAccountIDUserUserIDMetaflowGet (String accountID, String userID) throws TimeoutException, ExecutionException, InterruptedException, ApiException {
    Object postBody = null;
    // verify the required parameter 'accountID' is set
    if (accountID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'accountID' when calling v1AccountAccountIDUserUserIDMetaflowGet",
        new ApiException(400, "Missing the required parameter 'accountID' when calling v1AccountAccountIDUserUserIDMetaflowGet"));
    }
    // verify the required parameter 'userID' is set
    if (userID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'userID' when calling v1AccountAccountIDUserUserIDMetaflowGet",
        new ApiException(400, "Missing the required parameter 'userID' when calling v1AccountAccountIDUserUserIDMetaflowGet"));
    }

    // create path and map variables
    String path = "/v1/account/{accountID}/user/{userID}/metaflow".replaceAll("\\{" + "accountID" + "\\}", apiInvoker.escapeString(accountID.toString())).replaceAll("\\{" + "userID" + "\\}", apiInvoker.escapeString(userID.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();
    String[] contentTypes = {
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
    }

    String[] authNames = new String[] { "BearerAuth" };

    try {
      String localVarResponse = apiInvoker.invokeAPI (basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames);
      if (localVarResponse != null) {
         return (ServiceDocsMetaflowGet) ApiInvoker.deserialize(localVarResponse, "", ServiceDocsMetaflowGet.class);
      } else {
         return null;
      }
    } catch (ApiException ex) {
       throw ex;
    } catch (InterruptedException ex) {
       throw ex;
    } catch (ExecutionException ex) {
      if (ex.getCause() instanceof VolleyError) {
        VolleyError volleyError = (VolleyError)ex.getCause();
        if (volleyError.networkResponse != null) {
          throw new ApiException(volleyError.networkResponse.statusCode, volleyError.getMessage());
        }
      }
      throw ex;
    } catch (TimeoutException ex) {
      throw ex;
    }
  }

      /**
   * Get User Metaflow List
   * Get the list of metaflows for a user.
   * @param accountID Account ID, 32 alpha numeric   * @param userID user ID, 32 alpha numeric
  */
  public void v1AccountAccountIDUserUserIDMetaflowGet (String accountID, String userID, final Response.Listener<ServiceDocsMetaflowGet> responseListener, final Response.ErrorListener errorListener) {
    Object postBody = null;

    // verify the required parameter 'accountID' is set
    if (accountID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'accountID' when calling v1AccountAccountIDUserUserIDMetaflowGet",
        new ApiException(400, "Missing the required parameter 'accountID' when calling v1AccountAccountIDUserUserIDMetaflowGet"));
    }
    // verify the required parameter 'userID' is set
    if (userID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'userID' when calling v1AccountAccountIDUserUserIDMetaflowGet",
        new ApiException(400, "Missing the required parameter 'userID' when calling v1AccountAccountIDUserUserIDMetaflowGet"));
    }

    // create path and map variables
    String path = "/v1/account/{accountID}/user/{userID}/metaflow".replaceAll("\\{format\\}","json").replaceAll("\\{" + "accountID" + "\\}", apiInvoker.escapeString(accountID.toString())).replaceAll("\\{" + "userID" + "\\}", apiInvoker.escapeString(userID.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();



    String[] contentTypes = {
      
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
          }

    String[] authNames = new String[] { "BearerAuth" };

    try {
      apiInvoker.invokeAPI(basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames,
        new Response.Listener<String>() {
          @Override
          public void onResponse(String localVarResponse) {
            try {
              responseListener.onResponse((ServiceDocsMetaflowGet) ApiInvoker.deserialize(localVarResponse,  "", ServiceDocsMetaflowGet.class));
            } catch (ApiException exception) {
               errorListener.onErrorResponse(new VolleyError(exception));
            }
          }
      }, new Response.ErrorListener() {
          @Override
          public void onErrorResponse(VolleyError error) {
            errorListener.onErrorResponse(error);
          }
      });
    } catch (ApiException ex) {
      errorListener.onErrorResponse(new VolleyError(ex));
    }
  }
  /**
  * Create User Metaflow
  * Add a metaflow or multiple metaflows for a user in an account.
   * @param accountID Account ID, 32 alpha numeric
   * @param userID user ID, 32 alpha numeric
   * @param reqBody payload fields
   * @return ServiceDocsMetaflowGet
  */
  public ServiceDocsMetaflowGet v1AccountAccountIDUserUserIDMetaflowPost (String accountID, String userID, ServiceVOIPMetaflowAddData reqBody) throws TimeoutException, ExecutionException, InterruptedException, ApiException {
    Object postBody = reqBody;
    // verify the required parameter 'accountID' is set
    if (accountID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'accountID' when calling v1AccountAccountIDUserUserIDMetaflowPost",
        new ApiException(400, "Missing the required parameter 'accountID' when calling v1AccountAccountIDUserUserIDMetaflowPost"));
    }
    // verify the required parameter 'userID' is set
    if (userID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'userID' when calling v1AccountAccountIDUserUserIDMetaflowPost",
        new ApiException(400, "Missing the required parameter 'userID' when calling v1AccountAccountIDUserUserIDMetaflowPost"));
    }
    // verify the required parameter 'reqBody' is set
    if (reqBody == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'reqBody' when calling v1AccountAccountIDUserUserIDMetaflowPost",
        new ApiException(400, "Missing the required parameter 'reqBody' when calling v1AccountAccountIDUserUserIDMetaflowPost"));
    }

    // create path and map variables
    String path = "/v1/account/{accountID}/user/{userID}/metaflow".replaceAll("\\{" + "accountID" + "\\}", apiInvoker.escapeString(accountID.toString())).replaceAll("\\{" + "userID" + "\\}", apiInvoker.escapeString(userID.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();
    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
    }

    String[] authNames = new String[] { "BearerAuth" };

    try {
      String localVarResponse = apiInvoker.invokeAPI (basePath, path, "POST", queryParams, postBody, headerParams, formParams, contentType, authNames);
      if (localVarResponse != null) {
         return (ServiceDocsMetaflowGet) ApiInvoker.deserialize(localVarResponse, "", ServiceDocsMetaflowGet.class);
      } else {
         return null;
      }
    } catch (ApiException ex) {
       throw ex;
    } catch (InterruptedException ex) {
       throw ex;
    } catch (ExecutionException ex) {
      if (ex.getCause() instanceof VolleyError) {
        VolleyError volleyError = (VolleyError)ex.getCause();
        if (volleyError.networkResponse != null) {
          throw new ApiException(volleyError.networkResponse.statusCode, volleyError.getMessage());
        }
      }
      throw ex;
    } catch (TimeoutException ex) {
      throw ex;
    }
  }

      /**
   * Create User Metaflow
   * Add a metaflow or multiple metaflows for a user in an account.
   * @param accountID Account ID, 32 alpha numeric   * @param userID user ID, 32 alpha numeric   * @param reqBody payload fields
  */
  public void v1AccountAccountIDUserUserIDMetaflowPost (String accountID, String userID, ServiceVOIPMetaflowAddData reqBody, final Response.Listener<ServiceDocsMetaflowGet> responseListener, final Response.ErrorListener errorListener) {
    Object postBody = reqBody;

    // verify the required parameter 'accountID' is set
    if (accountID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'accountID' when calling v1AccountAccountIDUserUserIDMetaflowPost",
        new ApiException(400, "Missing the required parameter 'accountID' when calling v1AccountAccountIDUserUserIDMetaflowPost"));
    }
    // verify the required parameter 'userID' is set
    if (userID == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'userID' when calling v1AccountAccountIDUserUserIDMetaflowPost",
        new ApiException(400, "Missing the required parameter 'userID' when calling v1AccountAccountIDUserUserIDMetaflowPost"));
    }
    // verify the required parameter 'reqBody' is set
    if (reqBody == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'reqBody' when calling v1AccountAccountIDUserUserIDMetaflowPost",
        new ApiException(400, "Missing the required parameter 'reqBody' when calling v1AccountAccountIDUserUserIDMetaflowPost"));
    }

    // create path and map variables
    String path = "/v1/account/{accountID}/user/{userID}/metaflow".replaceAll("\\{format\\}","json").replaceAll("\\{" + "accountID" + "\\}", apiInvoker.escapeString(accountID.toString())).replaceAll("\\{" + "userID" + "\\}", apiInvoker.escapeString(userID.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();



    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
          }

    String[] authNames = new String[] { "BearerAuth" };

    try {
      apiInvoker.invokeAPI(basePath, path, "POST", queryParams, postBody, headerParams, formParams, contentType, authNames,
        new Response.Listener<String>() {
          @Override
          public void onResponse(String localVarResponse) {
            try {
              responseListener.onResponse((ServiceDocsMetaflowGet) ApiInvoker.deserialize(localVarResponse,  "", ServiceDocsMetaflowGet.class));
            } catch (ApiException exception) {
               errorListener.onErrorResponse(new VolleyError(exception));
            }
          }
      }, new Response.ErrorListener() {
          @Override
          public void onErrorResponse(VolleyError error) {
            errorListener.onErrorResponse(error);
          }
      });
    } catch (ApiException ex) {
      errorListener.onErrorResponse(new VolleyError(ex));
    }
  }
}
