/**
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import org.openapitools.client.model.ModelsAccountOutputFullCalleridEmergency;
import org.openapitools.client.model.ModelsAccountOutputFullCalleridExternal;
import org.openapitools.client.model.ModelsAccountOutputFullCalleridInternal;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ModelsVOIPAccountOutputFullCallerid {
  
  @SerializedName("emergency")
  private ModelsAccountOutputFullCalleridEmergency emergency = null;
  @SerializedName("external")
  private ModelsAccountOutputFullCalleridExternal external = null;
  @SerializedName("internal")
  private ModelsAccountOutputFullCalleridInternal internal = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public ModelsAccountOutputFullCalleridEmergency getEmergency() {
    return emergency;
  }
  public void setEmergency(ModelsAccountOutputFullCalleridEmergency emergency) {
    this.emergency = emergency;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ModelsAccountOutputFullCalleridExternal getExternal() {
    return external;
  }
  public void setExternal(ModelsAccountOutputFullCalleridExternal external) {
    this.external = external;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ModelsAccountOutputFullCalleridInternal getInternal() {
    return internal;
  }
  public void setInternal(ModelsAccountOutputFullCalleridInternal internal) {
    this.internal = internal;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelsVOIPAccountOutputFullCallerid modelsVOIPAccountOutputFullCallerid = (ModelsVOIPAccountOutputFullCallerid) o;
    return (this.emergency == null ? modelsVOIPAccountOutputFullCallerid.emergency == null : this.emergency.equals(modelsVOIPAccountOutputFullCallerid.emergency)) &&
        (this.external == null ? modelsVOIPAccountOutputFullCallerid.external == null : this.external.equals(modelsVOIPAccountOutputFullCallerid.external)) &&
        (this.internal == null ? modelsVOIPAccountOutputFullCallerid.internal == null : this.internal.equals(modelsVOIPAccountOutputFullCallerid.internal));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.emergency == null ? 0: this.emergency.hashCode());
    result = 31 * result + (this.external == null ? 0: this.external.hashCode());
    result = 31 * result + (this.internal == null ? 0: this.internal.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelsVOIPAccountOutputFullCallerid {\n");
    
    sb.append("  emergency: ").append(emergency).append("\n");
    sb.append("  external: ").append(external).append("\n");
    sb.append("  internal: ").append(internal).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
