/**
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ModelsLineKeyProcessedTempData {
  
  @SerializedName("label")
  private String label = null;
  @SerializedName("line")
  private Integer line = null;
  @SerializedName("type")
  private String type = null;
  @SerializedName("value")
  private String value = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLabel() {
    return label;
  }
  public void setLabel(String label) {
    this.label = label;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getLine() {
    return line;
  }
  public void setLine(Integer line) {
    this.line = line;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }
  public void setType(String type) {
    this.type = type;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getValue() {
    return value;
  }
  public void setValue(String value) {
    this.value = value;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelsLineKeyProcessedTempData modelsLineKeyProcessedTempData = (ModelsLineKeyProcessedTempData) o;
    return (this.label == null ? modelsLineKeyProcessedTempData.label == null : this.label.equals(modelsLineKeyProcessedTempData.label)) &&
        (this.line == null ? modelsLineKeyProcessedTempData.line == null : this.line.equals(modelsLineKeyProcessedTempData.line)) &&
        (this.type == null ? modelsLineKeyProcessedTempData.type == null : this.type.equals(modelsLineKeyProcessedTempData.type)) &&
        (this.value == null ? modelsLineKeyProcessedTempData.value == null : this.value.equals(modelsLineKeyProcessedTempData.value));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.label == null ? 0: this.label.hashCode());
    result = 31 * result + (this.line == null ? 0: this.line.hashCode());
    result = 31 * result + (this.type == null ? 0: this.type.hashCode());
    result = 31 * result + (this.value == null ? 0: this.value.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelsLineKeyProcessedTempData {\n");
    
    sb.append("  label: ").append(label).append("\n");
    sb.append("  line: ").append(line).append("\n");
    sb.append("  type: ").append(type).append("\n");
    sb.append("  value: ").append(value).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
