/**
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import org.openapitools.client.model.ModelsConfigFileParameter;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ModelsGenerateConfigFileRequest {
  
  @SerializedName("parameters")
  private ModelsConfigFileParameter parameters = null;
  @SerializedName("template_file_id")
  private String templateFileId = null;
  @SerializedName("template_id")
  private String templateId = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public ModelsConfigFileParameter getParameters() {
    return parameters;
  }
  public void setParameters(ModelsConfigFileParameter parameters) {
    this.parameters = parameters;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getTemplateFileId() {
    return templateFileId;
  }
  public void setTemplateFileId(String templateFileId) {
    this.templateFileId = templateFileId;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getTemplateId() {
    return templateId;
  }
  public void setTemplateId(String templateId) {
    this.templateId = templateId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelsGenerateConfigFileRequest modelsGenerateConfigFileRequest = (ModelsGenerateConfigFileRequest) o;
    return (this.parameters == null ? modelsGenerateConfigFileRequest.parameters == null : this.parameters.equals(modelsGenerateConfigFileRequest.parameters)) &&
        (this.templateFileId == null ? modelsGenerateConfigFileRequest.templateFileId == null : this.templateFileId.equals(modelsGenerateConfigFileRequest.templateFileId)) &&
        (this.templateId == null ? modelsGenerateConfigFileRequest.templateId == null : this.templateId.equals(modelsGenerateConfigFileRequest.templateId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.parameters == null ? 0: this.parameters.hashCode());
    result = 31 * result + (this.templateFileId == null ? 0: this.templateFileId.hashCode());
    result = 31 * result + (this.templateId == null ? 0: this.templateId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelsGenerateConfigFileRequest {\n");
    
    sb.append("  parameters: ").append(parameters).append("\n");
    sb.append("  templateFileId: ").append(templateFileId).append("\n");
    sb.append("  templateId: ").append(templateId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
