/**
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.Map;
import org.openapitools.client.model.OasAnyTypeNotMapped;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ServiceWebhookEdit {
  
  public enum CallbackMethodEnum {
     POST,  PUT, 
  };
  @SerializedName("callback_method")
  private CallbackMethodEnum callbackMethod = null;
  @SerializedName("callback_url")
  private String callbackUrl = null;
  @SerializedName("data")
  private Map<String, OasAnyTypeNotMapped> data = null;
  @SerializedName("is_active")
  private Boolean isActive = null;
  @SerializedName("title")
  private String title = null;
  @SerializedName("webhook_type")
  private String webhookType = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public CallbackMethodEnum getCallbackMethod() {
    return callbackMethod;
  }
  public void setCallbackMethod(CallbackMethodEnum callbackMethod) {
    this.callbackMethod = callbackMethod;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getCallbackUrl() {
    return callbackUrl;
  }
  public void setCallbackUrl(String callbackUrl) {
    this.callbackUrl = callbackUrl;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Map<String, OasAnyTypeNotMapped> getData() {
    return data;
  }
  public void setData(Map<String, OasAnyTypeNotMapped> data) {
    this.data = data;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getIsActive() {
    return isActive;
  }
  public void setIsActive(Boolean isActive) {
    this.isActive = isActive;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getTitle() {
    return title;
  }
  public void setTitle(String title) {
    this.title = title;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getWebhookType() {
    return webhookType;
  }
  public void setWebhookType(String webhookType) {
    this.webhookType = webhookType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceWebhookEdit serviceWebhookEdit = (ServiceWebhookEdit) o;
    return (this.callbackMethod == null ? serviceWebhookEdit.callbackMethod == null : this.callbackMethod.equals(serviceWebhookEdit.callbackMethod)) &&
        (this.callbackUrl == null ? serviceWebhookEdit.callbackUrl == null : this.callbackUrl.equals(serviceWebhookEdit.callbackUrl)) &&
        (this.data == null ? serviceWebhookEdit.data == null : this.data.equals(serviceWebhookEdit.data)) &&
        (this.isActive == null ? serviceWebhookEdit.isActive == null : this.isActive.equals(serviceWebhookEdit.isActive)) &&
        (this.title == null ? serviceWebhookEdit.title == null : this.title.equals(serviceWebhookEdit.title)) &&
        (this.webhookType == null ? serviceWebhookEdit.webhookType == null : this.webhookType.equals(serviceWebhookEdit.webhookType));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.callbackMethod == null ? 0: this.callbackMethod.hashCode());
    result = 31 * result + (this.callbackUrl == null ? 0: this.callbackUrl.hashCode());
    result = 31 * result + (this.data == null ? 0: this.data.hashCode());
    result = 31 * result + (this.isActive == null ? 0: this.isActive.hashCode());
    result = 31 * result + (this.title == null ? 0: this.title.hashCode());
    result = 31 * result + (this.webhookType == null ? 0: this.webhookType.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceWebhookEdit {\n");
    
    sb.append("  callbackMethod: ").append(callbackMethod).append("\n");
    sb.append("  callbackUrl: ").append(callbackUrl).append("\n");
    sb.append("  data: ").append(data).append("\n");
    sb.append("  isActive: ").append(isActive).append("\n");
    sb.append("  title: ").append(title).append("\n");
    sb.append("  webhookType: ").append(webhookType).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
