/**
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.Map;
import org.openapitools.client.model.OasAnyTypeNotMapped;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ServiceChannelOutput {
  
  @SerializedName("answered")
  private Boolean answered = null;
  @SerializedName("authorizing_id")
  private String authorizingId = null;
  @SerializedName("authorizing_type")
  private String authorizingType = null;
  @SerializedName("callflow_id")
  private String callflowId = null;
  @SerializedName("channel_authorized")
  private Boolean channelAuthorized = null;
  @SerializedName("custom_application_vars")
  private Map<String, OasAnyTypeNotMapped> customApplicationVars = null;
  @SerializedName("custom_auth_headers")
  private Map<String, OasAnyTypeNotMapped> customAuthHeaders = null;
  @SerializedName("custom_channel_vars")
  private Map<String, OasAnyTypeNotMapped> customChannelVars = null;
  @SerializedName("custom_sip_headers")
  private Map<String, OasAnyTypeNotMapped> customSipHeaders = null;
  @SerializedName("destination")
  private String destination = null;
  @SerializedName("direction")
  private String direction = null;
  @SerializedName("elapsed_s")
  private Integer elapsedS = null;
  @SerializedName("from_tag")
  private String fromTag = null;
  @SerializedName("interaction_id")
  private String interactionId = null;
  @SerializedName("is_loopback")
  private Boolean isLoopback = null;
  @SerializedName("is_onhold")
  private Boolean isOnhold = null;
  @SerializedName("other_leg")
  private String otherLeg = null;
  @SerializedName("owner_id")
  private String ownerId = null;
  @SerializedName("presence_id")
  private String presenceId = null;
  @SerializedName("request")
  private String request = null;
  @SerializedName("reseller_id")
  private String resellerId = null;
  @SerializedName("timestamp")
  private Integer timestamp = null;
  @SerializedName("to_tag")
  private String toTag = null;
  @SerializedName("username")
  private String username = null;
  @SerializedName("uuid")
  private String uuid = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getAnswered() {
    return answered;
  }
  public void setAnswered(Boolean answered) {
    this.answered = answered;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAuthorizingId() {
    return authorizingId;
  }
  public void setAuthorizingId(String authorizingId) {
    this.authorizingId = authorizingId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAuthorizingType() {
    return authorizingType;
  }
  public void setAuthorizingType(String authorizingType) {
    this.authorizingType = authorizingType;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCallflowId() {
    return callflowId;
  }
  public void setCallflowId(String callflowId) {
    this.callflowId = callflowId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getChannelAuthorized() {
    return channelAuthorized;
  }
  public void setChannelAuthorized(Boolean channelAuthorized) {
    this.channelAuthorized = channelAuthorized;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Map<String, OasAnyTypeNotMapped> getCustomApplicationVars() {
    return customApplicationVars;
  }
  public void setCustomApplicationVars(Map<String, OasAnyTypeNotMapped> customApplicationVars) {
    this.customApplicationVars = customApplicationVars;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Map<String, OasAnyTypeNotMapped> getCustomAuthHeaders() {
    return customAuthHeaders;
  }
  public void setCustomAuthHeaders(Map<String, OasAnyTypeNotMapped> customAuthHeaders) {
    this.customAuthHeaders = customAuthHeaders;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Map<String, OasAnyTypeNotMapped> getCustomChannelVars() {
    return customChannelVars;
  }
  public void setCustomChannelVars(Map<String, OasAnyTypeNotMapped> customChannelVars) {
    this.customChannelVars = customChannelVars;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Map<String, OasAnyTypeNotMapped> getCustomSipHeaders() {
    return customSipHeaders;
  }
  public void setCustomSipHeaders(Map<String, OasAnyTypeNotMapped> customSipHeaders) {
    this.customSipHeaders = customSipHeaders;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDestination() {
    return destination;
  }
  public void setDestination(String destination) {
    this.destination = destination;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDirection() {
    return direction;
  }
  public void setDirection(String direction) {
    this.direction = direction;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getElapsedS() {
    return elapsedS;
  }
  public void setElapsedS(Integer elapsedS) {
    this.elapsedS = elapsedS;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getFromTag() {
    return fromTag;
  }
  public void setFromTag(String fromTag) {
    this.fromTag = fromTag;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getInteractionId() {
    return interactionId;
  }
  public void setInteractionId(String interactionId) {
    this.interactionId = interactionId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getIsLoopback() {
    return isLoopback;
  }
  public void setIsLoopback(Boolean isLoopback) {
    this.isLoopback = isLoopback;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getIsOnhold() {
    return isOnhold;
  }
  public void setIsOnhold(Boolean isOnhold) {
    this.isOnhold = isOnhold;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getOtherLeg() {
    return otherLeg;
  }
  public void setOtherLeg(String otherLeg) {
    this.otherLeg = otherLeg;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getOwnerId() {
    return ownerId;
  }
  public void setOwnerId(String ownerId) {
    this.ownerId = ownerId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPresenceId() {
    return presenceId;
  }
  public void setPresenceId(String presenceId) {
    this.presenceId = presenceId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getRequest() {
    return request;
  }
  public void setRequest(String request) {
    this.request = request;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getResellerId() {
    return resellerId;
  }
  public void setResellerId(String resellerId) {
    this.resellerId = resellerId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getTimestamp() {
    return timestamp;
  }
  public void setTimestamp(Integer timestamp) {
    this.timestamp = timestamp;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getToTag() {
    return toTag;
  }
  public void setToTag(String toTag) {
    this.toTag = toTag;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUsername() {
    return username;
  }
  public void setUsername(String username) {
    this.username = username;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUuid() {
    return uuid;
  }
  public void setUuid(String uuid) {
    this.uuid = uuid;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceChannelOutput serviceChannelOutput = (ServiceChannelOutput) o;
    return (this.answered == null ? serviceChannelOutput.answered == null : this.answered.equals(serviceChannelOutput.answered)) &&
        (this.authorizingId == null ? serviceChannelOutput.authorizingId == null : this.authorizingId.equals(serviceChannelOutput.authorizingId)) &&
        (this.authorizingType == null ? serviceChannelOutput.authorizingType == null : this.authorizingType.equals(serviceChannelOutput.authorizingType)) &&
        (this.callflowId == null ? serviceChannelOutput.callflowId == null : this.callflowId.equals(serviceChannelOutput.callflowId)) &&
        (this.channelAuthorized == null ? serviceChannelOutput.channelAuthorized == null : this.channelAuthorized.equals(serviceChannelOutput.channelAuthorized)) &&
        (this.customApplicationVars == null ? serviceChannelOutput.customApplicationVars == null : this.customApplicationVars.equals(serviceChannelOutput.customApplicationVars)) &&
        (this.customAuthHeaders == null ? serviceChannelOutput.customAuthHeaders == null : this.customAuthHeaders.equals(serviceChannelOutput.customAuthHeaders)) &&
        (this.customChannelVars == null ? serviceChannelOutput.customChannelVars == null : this.customChannelVars.equals(serviceChannelOutput.customChannelVars)) &&
        (this.customSipHeaders == null ? serviceChannelOutput.customSipHeaders == null : this.customSipHeaders.equals(serviceChannelOutput.customSipHeaders)) &&
        (this.destination == null ? serviceChannelOutput.destination == null : this.destination.equals(serviceChannelOutput.destination)) &&
        (this.direction == null ? serviceChannelOutput.direction == null : this.direction.equals(serviceChannelOutput.direction)) &&
        (this.elapsedS == null ? serviceChannelOutput.elapsedS == null : this.elapsedS.equals(serviceChannelOutput.elapsedS)) &&
        (this.fromTag == null ? serviceChannelOutput.fromTag == null : this.fromTag.equals(serviceChannelOutput.fromTag)) &&
        (this.interactionId == null ? serviceChannelOutput.interactionId == null : this.interactionId.equals(serviceChannelOutput.interactionId)) &&
        (this.isLoopback == null ? serviceChannelOutput.isLoopback == null : this.isLoopback.equals(serviceChannelOutput.isLoopback)) &&
        (this.isOnhold == null ? serviceChannelOutput.isOnhold == null : this.isOnhold.equals(serviceChannelOutput.isOnhold)) &&
        (this.otherLeg == null ? serviceChannelOutput.otherLeg == null : this.otherLeg.equals(serviceChannelOutput.otherLeg)) &&
        (this.ownerId == null ? serviceChannelOutput.ownerId == null : this.ownerId.equals(serviceChannelOutput.ownerId)) &&
        (this.presenceId == null ? serviceChannelOutput.presenceId == null : this.presenceId.equals(serviceChannelOutput.presenceId)) &&
        (this.request == null ? serviceChannelOutput.request == null : this.request.equals(serviceChannelOutput.request)) &&
        (this.resellerId == null ? serviceChannelOutput.resellerId == null : this.resellerId.equals(serviceChannelOutput.resellerId)) &&
        (this.timestamp == null ? serviceChannelOutput.timestamp == null : this.timestamp.equals(serviceChannelOutput.timestamp)) &&
        (this.toTag == null ? serviceChannelOutput.toTag == null : this.toTag.equals(serviceChannelOutput.toTag)) &&
        (this.username == null ? serviceChannelOutput.username == null : this.username.equals(serviceChannelOutput.username)) &&
        (this.uuid == null ? serviceChannelOutput.uuid == null : this.uuid.equals(serviceChannelOutput.uuid));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.answered == null ? 0: this.answered.hashCode());
    result = 31 * result + (this.authorizingId == null ? 0: this.authorizingId.hashCode());
    result = 31 * result + (this.authorizingType == null ? 0: this.authorizingType.hashCode());
    result = 31 * result + (this.callflowId == null ? 0: this.callflowId.hashCode());
    result = 31 * result + (this.channelAuthorized == null ? 0: this.channelAuthorized.hashCode());
    result = 31 * result + (this.customApplicationVars == null ? 0: this.customApplicationVars.hashCode());
    result = 31 * result + (this.customAuthHeaders == null ? 0: this.customAuthHeaders.hashCode());
    result = 31 * result + (this.customChannelVars == null ? 0: this.customChannelVars.hashCode());
    result = 31 * result + (this.customSipHeaders == null ? 0: this.customSipHeaders.hashCode());
    result = 31 * result + (this.destination == null ? 0: this.destination.hashCode());
    result = 31 * result + (this.direction == null ? 0: this.direction.hashCode());
    result = 31 * result + (this.elapsedS == null ? 0: this.elapsedS.hashCode());
    result = 31 * result + (this.fromTag == null ? 0: this.fromTag.hashCode());
    result = 31 * result + (this.interactionId == null ? 0: this.interactionId.hashCode());
    result = 31 * result + (this.isLoopback == null ? 0: this.isLoopback.hashCode());
    result = 31 * result + (this.isOnhold == null ? 0: this.isOnhold.hashCode());
    result = 31 * result + (this.otherLeg == null ? 0: this.otherLeg.hashCode());
    result = 31 * result + (this.ownerId == null ? 0: this.ownerId.hashCode());
    result = 31 * result + (this.presenceId == null ? 0: this.presenceId.hashCode());
    result = 31 * result + (this.request == null ? 0: this.request.hashCode());
    result = 31 * result + (this.resellerId == null ? 0: this.resellerId.hashCode());
    result = 31 * result + (this.timestamp == null ? 0: this.timestamp.hashCode());
    result = 31 * result + (this.toTag == null ? 0: this.toTag.hashCode());
    result = 31 * result + (this.username == null ? 0: this.username.hashCode());
    result = 31 * result + (this.uuid == null ? 0: this.uuid.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceChannelOutput {\n");
    
    sb.append("  answered: ").append(answered).append("\n");
    sb.append("  authorizingId: ").append(authorizingId).append("\n");
    sb.append("  authorizingType: ").append(authorizingType).append("\n");
    sb.append("  callflowId: ").append(callflowId).append("\n");
    sb.append("  channelAuthorized: ").append(channelAuthorized).append("\n");
    sb.append("  customApplicationVars: ").append(customApplicationVars).append("\n");
    sb.append("  customAuthHeaders: ").append(customAuthHeaders).append("\n");
    sb.append("  customChannelVars: ").append(customChannelVars).append("\n");
    sb.append("  customSipHeaders: ").append(customSipHeaders).append("\n");
    sb.append("  destination: ").append(destination).append("\n");
    sb.append("  direction: ").append(direction).append("\n");
    sb.append("  elapsedS: ").append(elapsedS).append("\n");
    sb.append("  fromTag: ").append(fromTag).append("\n");
    sb.append("  interactionId: ").append(interactionId).append("\n");
    sb.append("  isLoopback: ").append(isLoopback).append("\n");
    sb.append("  isOnhold: ").append(isOnhold).append("\n");
    sb.append("  otherLeg: ").append(otherLeg).append("\n");
    sb.append("  ownerId: ").append(ownerId).append("\n");
    sb.append("  presenceId: ").append(presenceId).append("\n");
    sb.append("  request: ").append(request).append("\n");
    sb.append("  resellerId: ").append(resellerId).append("\n");
    sb.append("  timestamp: ").append(timestamp).append("\n");
    sb.append("  toTag: ").append(toTag).append("\n");
    sb.append("  username: ").append(username).append("\n");
    sb.append("  uuid: ").append(uuid).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
