/**
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import org.openapitools.client.model.ServiceE911RemoveLocationStatus;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ServiceE911RemoveLocationOutput {
  
  @SerializedName("location_status")
  private ServiceE911RemoveLocationStatus locationStatus = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public ServiceE911RemoveLocationStatus getLocationStatus() {
    return locationStatus;
  }
  public void setLocationStatus(ServiceE911RemoveLocationStatus locationStatus) {
    this.locationStatus = locationStatus;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceE911RemoveLocationOutput serviceE911RemoveLocationOutput = (ServiceE911RemoveLocationOutput) o;
    return (this.locationStatus == null ? serviceE911RemoveLocationOutput.locationStatus == null : this.locationStatus.equals(serviceE911RemoveLocationOutput.locationStatus));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.locationStatus == null ? 0: this.locationStatus.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceE911RemoveLocationOutput {\n");
    
    sb.append("  locationStatus: ").append(locationStatus).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
