/**
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.Map;
import org.openapitools.client.model.OasAnyTypeNotMapped;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ServiceVOIPCallQueueAddEditData {
  
  @SerializedName("agent_wrapup_time")
  private Integer agentWrapupTime = null;
  @SerializedName("features")
  private Map<String, OasAnyTypeNotMapped> features = null;
  @SerializedName("force_away_on_reject")
  private Boolean forceAwayOnReject = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("queue_router")
  private String queueRouter = null;
  @SerializedName("queue_type")
  private String queueType = null;
  @SerializedName("ring_timeout")
  private Integer ringTimeout = null;
  @SerializedName("tick_time")
  private Integer tickTime = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getAgentWrapupTime() {
    return agentWrapupTime;
  }
  public void setAgentWrapupTime(Integer agentWrapupTime) {
    this.agentWrapupTime = agentWrapupTime;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Map<String, OasAnyTypeNotMapped> getFeatures() {
    return features;
  }
  public void setFeatures(Map<String, OasAnyTypeNotMapped> features) {
    this.features = features;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getForceAwayOnReject() {
    return forceAwayOnReject;
  }
  public void setForceAwayOnReject(Boolean forceAwayOnReject) {
    this.forceAwayOnReject = forceAwayOnReject;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getQueueRouter() {
    return queueRouter;
  }
  public void setQueueRouter(String queueRouter) {
    this.queueRouter = queueRouter;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getQueueType() {
    return queueType;
  }
  public void setQueueType(String queueType) {
    this.queueType = queueType;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getRingTimeout() {
    return ringTimeout;
  }
  public void setRingTimeout(Integer ringTimeout) {
    this.ringTimeout = ringTimeout;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getTickTime() {
    return tickTime;
  }
  public void setTickTime(Integer tickTime) {
    this.tickTime = tickTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceVOIPCallQueueAddEditData serviceVOIPCallQueueAddEditData = (ServiceVOIPCallQueueAddEditData) o;
    return (this.agentWrapupTime == null ? serviceVOIPCallQueueAddEditData.agentWrapupTime == null : this.agentWrapupTime.equals(serviceVOIPCallQueueAddEditData.agentWrapupTime)) &&
        (this.features == null ? serviceVOIPCallQueueAddEditData.features == null : this.features.equals(serviceVOIPCallQueueAddEditData.features)) &&
        (this.forceAwayOnReject == null ? serviceVOIPCallQueueAddEditData.forceAwayOnReject == null : this.forceAwayOnReject.equals(serviceVOIPCallQueueAddEditData.forceAwayOnReject)) &&
        (this.name == null ? serviceVOIPCallQueueAddEditData.name == null : this.name.equals(serviceVOIPCallQueueAddEditData.name)) &&
        (this.queueRouter == null ? serviceVOIPCallQueueAddEditData.queueRouter == null : this.queueRouter.equals(serviceVOIPCallQueueAddEditData.queueRouter)) &&
        (this.queueType == null ? serviceVOIPCallQueueAddEditData.queueType == null : this.queueType.equals(serviceVOIPCallQueueAddEditData.queueType)) &&
        (this.ringTimeout == null ? serviceVOIPCallQueueAddEditData.ringTimeout == null : this.ringTimeout.equals(serviceVOIPCallQueueAddEditData.ringTimeout)) &&
        (this.tickTime == null ? serviceVOIPCallQueueAddEditData.tickTime == null : this.tickTime.equals(serviceVOIPCallQueueAddEditData.tickTime));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.agentWrapupTime == null ? 0: this.agentWrapupTime.hashCode());
    result = 31 * result + (this.features == null ? 0: this.features.hashCode());
    result = 31 * result + (this.forceAwayOnReject == null ? 0: this.forceAwayOnReject.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.queueRouter == null ? 0: this.queueRouter.hashCode());
    result = 31 * result + (this.queueType == null ? 0: this.queueType.hashCode());
    result = 31 * result + (this.ringTimeout == null ? 0: this.ringTimeout.hashCode());
    result = 31 * result + (this.tickTime == null ? 0: this.tickTime.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceVOIPCallQueueAddEditData {\n");
    
    sb.append("  agentWrapupTime: ").append(agentWrapupTime).append("\n");
    sb.append("  features: ").append(features).append("\n");
    sb.append("  forceAwayOnReject: ").append(forceAwayOnReject).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  queueRouter: ").append(queueRouter).append("\n");
    sb.append("  queueType: ").append(queueType).append("\n");
    sb.append("  ringTimeout: ").append(ringTimeout).append("\n");
    sb.append("  tickTime: ").append(tickTime).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
