/**
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import org.openapitools.client.model.ModelsVOIPAccountMusicOnHold;
import org.openapitools.client.model.ModelsVOIPAccountOutputFullCallerid;
import org.openapitools.client.model.ModelsVOIPSharedDoNotDisturb;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ServiceVOIPAccountAddData {
  
  @SerializedName("caller_id")
  private ModelsVOIPAccountOutputFullCallerid callerId = null;
  @SerializedName("do_not_disturb")
  private ModelsVOIPSharedDoNotDisturb doNotDisturb = null;
  @SerializedName("music_on_hold")
  private ModelsVOIPAccountMusicOnHold musicOnHold = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("realm")
  private String realm = null;
  @SerializedName("timezone")
  private String timezone = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public ModelsVOIPAccountOutputFullCallerid getCallerId() {
    return callerId;
  }
  public void setCallerId(ModelsVOIPAccountOutputFullCallerid callerId) {
    this.callerId = callerId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ModelsVOIPSharedDoNotDisturb getDoNotDisturb() {
    return doNotDisturb;
  }
  public void setDoNotDisturb(ModelsVOIPSharedDoNotDisturb doNotDisturb) {
    this.doNotDisturb = doNotDisturb;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ModelsVOIPAccountMusicOnHold getMusicOnHold() {
    return musicOnHold;
  }
  public void setMusicOnHold(ModelsVOIPAccountMusicOnHold musicOnHold) {
    this.musicOnHold = musicOnHold;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getRealm() {
    return realm;
  }
  public void setRealm(String realm) {
    this.realm = realm;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getTimezone() {
    return timezone;
  }
  public void setTimezone(String timezone) {
    this.timezone = timezone;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceVOIPAccountAddData serviceVOIPAccountAddData = (ServiceVOIPAccountAddData) o;
    return (this.callerId == null ? serviceVOIPAccountAddData.callerId == null : this.callerId.equals(serviceVOIPAccountAddData.callerId)) &&
        (this.doNotDisturb == null ? serviceVOIPAccountAddData.doNotDisturb == null : this.doNotDisturb.equals(serviceVOIPAccountAddData.doNotDisturb)) &&
        (this.musicOnHold == null ? serviceVOIPAccountAddData.musicOnHold == null : this.musicOnHold.equals(serviceVOIPAccountAddData.musicOnHold)) &&
        (this.name == null ? serviceVOIPAccountAddData.name == null : this.name.equals(serviceVOIPAccountAddData.name)) &&
        (this.realm == null ? serviceVOIPAccountAddData.realm == null : this.realm.equals(serviceVOIPAccountAddData.realm)) &&
        (this.timezone == null ? serviceVOIPAccountAddData.timezone == null : this.timezone.equals(serviceVOIPAccountAddData.timezone));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.callerId == null ? 0: this.callerId.hashCode());
    result = 31 * result + (this.doNotDisturb == null ? 0: this.doNotDisturb.hashCode());
    result = 31 * result + (this.musicOnHold == null ? 0: this.musicOnHold.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.realm == null ? 0: this.realm.hashCode());
    result = 31 * result + (this.timezone == null ? 0: this.timezone.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceVOIPAccountAddData {\n");
    
    sb.append("  callerId: ").append(callerId).append("\n");
    sb.append("  doNotDisturb: ").append(doNotDisturb).append("\n");
    sb.append("  musicOnHold: ").append(musicOnHold).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  realm: ").append(realm).append("\n");
    sb.append("  timezone: ").append(timezone).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
