/**
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ServiceSystemStatusMessagingService {
  
  @SerializedName("messaging_server")
  private String messagingServer = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMessagingServer() {
    return messagingServer;
  }
  public void setMessagingServer(String messagingServer) {
    this.messagingServer = messagingServer;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceSystemStatusMessagingService serviceSystemStatusMessagingService = (ServiceSystemStatusMessagingService) o;
    return (this.messagingServer == null ? serviceSystemStatusMessagingService.messagingServer == null : this.messagingServer.equals(serviceSystemStatusMessagingService.messagingServer));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.messagingServer == null ? 0: this.messagingServer.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceSystemStatusMessagingService {\n");
    
    sb.append("  messagingServer: ").append(messagingServer).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
