/**
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ServiceSystemStatusSupportService {
  
  @SerializedName("e911_server")
  private String e911Server = null;
  @SerializedName("phone_number_server")
  private String phoneNumberServer = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getE911Server() {
    return e911Server;
  }
  public void setE911Server(String e911Server) {
    this.e911Server = e911Server;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPhoneNumberServer() {
    return phoneNumberServer;
  }
  public void setPhoneNumberServer(String phoneNumberServer) {
    this.phoneNumberServer = phoneNumberServer;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceSystemStatusSupportService serviceSystemStatusSupportService = (ServiceSystemStatusSupportService) o;
    return (this.e911Server == null ? serviceSystemStatusSupportService.e911Server == null : this.e911Server.equals(serviceSystemStatusSupportService.e911Server)) &&
        (this.phoneNumberServer == null ? serviceSystemStatusSupportService.phoneNumberServer == null : this.phoneNumberServer.equals(serviceSystemStatusSupportService.phoneNumberServer));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.e911Server == null ? 0: this.e911Server.hashCode());
    result = 31 * result + (this.phoneNumberServer == null ? 0: this.phoneNumberServer.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceSystemStatusSupportService {\n");
    
    sb.append("  e911Server: ").append(e911Server).append("\n");
    sb.append("  phoneNumberServer: ").append(phoneNumberServer).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
