/**
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import java.util.Map;
import org.openapitools.client.model.OasAnyTypeNotMapped;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ServiceStoragePlanDatabaseProperties {
  
  @SerializedName("create_options")
  private Map<String, OasAnyTypeNotMapped> createOptions = null;
  @SerializedName("names")
  private List<String> names = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Map<String, OasAnyTypeNotMapped> getCreateOptions() {
    return createOptions;
  }
  public void setCreateOptions(Map<String, OasAnyTypeNotMapped> createOptions) {
    this.createOptions = createOptions;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<String> getNames() {
    return names;
  }
  public void setNames(List<String> names) {
    this.names = names;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceStoragePlanDatabaseProperties serviceStoragePlanDatabaseProperties = (ServiceStoragePlanDatabaseProperties) o;
    return (this.createOptions == null ? serviceStoragePlanDatabaseProperties.createOptions == null : this.createOptions.equals(serviceStoragePlanDatabaseProperties.createOptions)) &&
        (this.names == null ? serviceStoragePlanDatabaseProperties.names == null : this.names.equals(serviceStoragePlanDatabaseProperties.names));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.createOptions == null ? 0: this.createOptions.hashCode());
    result = 31 * result + (this.names == null ? 0: this.names.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceStoragePlanDatabaseProperties {\n");
    
    sb.append("  createOptions: ").append(createOptions).append("\n");
    sb.append("  names: ").append(names).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
