/**
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import org.openapitools.client.model.ServiceSystemStatusOutput;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ServiceDocsSystemStatusGetSingle {
  
  @SerializedName("data")
  private ServiceSystemStatusOutput data = null;
  @SerializedName("request_id")
  private String requestId = null;
  @SerializedName("status_code")
  private Integer statusCode = null;
  @SerializedName("system_status")
  private String systemStatus = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public ServiceSystemStatusOutput getData() {
    return data;
  }
  public void setData(ServiceSystemStatusOutput data) {
    this.data = data;
  }

  /**
   * Unique id for each request
   **/
  @ApiModelProperty(value = "Unique id for each request")
  public String getRequestId() {
    return requestId;
  }
  public void setRequestId(String requestId) {
    this.requestId = requestId;
  }

  /**
   * HTTP response status code
   **/
  @ApiModelProperty(value = "HTTP response status code")
  public Integer getStatusCode() {
    return statusCode;
  }
  public void setStatusCode(Integer statusCode) {
    this.statusCode = statusCode;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSystemStatus() {
    return systemStatus;
  }
  public void setSystemStatus(String systemStatus) {
    this.systemStatus = systemStatus;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceDocsSystemStatusGetSingle serviceDocsSystemStatusGetSingle = (ServiceDocsSystemStatusGetSingle) o;
    return (this.data == null ? serviceDocsSystemStatusGetSingle.data == null : this.data.equals(serviceDocsSystemStatusGetSingle.data)) &&
        (this.requestId == null ? serviceDocsSystemStatusGetSingle.requestId == null : this.requestId.equals(serviceDocsSystemStatusGetSingle.requestId)) &&
        (this.statusCode == null ? serviceDocsSystemStatusGetSingle.statusCode == null : this.statusCode.equals(serviceDocsSystemStatusGetSingle.statusCode)) &&
        (this.systemStatus == null ? serviceDocsSystemStatusGetSingle.systemStatus == null : this.systemStatus.equals(serviceDocsSystemStatusGetSingle.systemStatus));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.data == null ? 0: this.data.hashCode());
    result = 31 * result + (this.requestId == null ? 0: this.requestId.hashCode());
    result = 31 * result + (this.statusCode == null ? 0: this.statusCode.hashCode());
    result = 31 * result + (this.systemStatus == null ? 0: this.systemStatus.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceDocsSystemStatusGetSingle {\n");
    
    sb.append("  data: ").append(data).append("\n");
    sb.append("  requestId: ").append(requestId).append("\n");
    sb.append("  statusCode: ").append(statusCode).append("\n");
    sb.append("  systemStatus: ").append(systemStatus).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
