/**
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import org.openapitools.client.model.ModelsCallForward;
import org.openapitools.client.model.ModelsMusicOnHold;
import org.openapitools.client.model.ModelsVOIPSharedDoNotDisturb;
import org.openapitools.client.model.ServiceVOIPDeviceAddEdit3a;
import org.openapitools.client.model.ServiceVOIPDeviceAddEdit3c;
import org.openapitools.client.model.ServiceVOIPDeviceAddEdit3d;
import org.openapitools.client.model.ServiceVOIPDeviceAddEditProvision;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ServiceVOIPDeviceAddEdit2 {
  
  @SerializedName("call_forward")
  private ModelsCallForward callForward = null;
  @SerializedName("caller_id")
  private ServiceVOIPDeviceAddEdit3c callerId = null;
  public enum DeviceTypeEnum {
     softphone,  sip_uri,  sip_device, 
  };
  @SerializedName("device_type")
  private DeviceTypeEnum deviceType = null;
  @SerializedName("do_not_disturb")
  private ModelsVOIPSharedDoNotDisturb doNotDisturb = null;
  @SerializedName("enabled")
  private Boolean enabled = null;
  @SerializedName("mac_address")
  private String macAddress = null;
  @SerializedName("media")
  private ServiceVOIPDeviceAddEdit3d media = null;
  @SerializedName("music_on_hold")
  private ModelsMusicOnHold musicOnHold = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("owner_id")
  private String ownerId = null;
  @SerializedName("provision")
  private ServiceVOIPDeviceAddEditProvision provision = null;
  @SerializedName("sip")
  private ServiceVOIPDeviceAddEdit3a sip = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public ModelsCallForward getCallForward() {
    return callForward;
  }
  public void setCallForward(ModelsCallForward callForward) {
    this.callForward = callForward;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ServiceVOIPDeviceAddEdit3c getCallerId() {
    return callerId;
  }
  public void setCallerId(ServiceVOIPDeviceAddEdit3c callerId) {
    this.callerId = callerId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public DeviceTypeEnum getDeviceType() {
    return deviceType;
  }
  public void setDeviceType(DeviceTypeEnum deviceType) {
    this.deviceType = deviceType;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ModelsVOIPSharedDoNotDisturb getDoNotDisturb() {
    return doNotDisturb;
  }
  public void setDoNotDisturb(ModelsVOIPSharedDoNotDisturb doNotDisturb) {
    this.doNotDisturb = doNotDisturb;
  }

  /**
   * cannot use required, else it has to be true and false is not allowed
   **/
  @ApiModelProperty(value = "cannot use required, else it has to be true and false is not allowed")
  public Boolean getEnabled() {
    return enabled;
  }
  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }

  /**
   * dont use mac, it enforces :, which voip does not like
   **/
  @ApiModelProperty(value = "dont use mac, it enforces :, which voip does not like")
  public String getMacAddress() {
    return macAddress;
  }
  public void setMacAddress(String macAddress) {
    this.macAddress = macAddress;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ServiceVOIPDeviceAddEdit3d getMedia() {
    return media;
  }
  public void setMedia(ServiceVOIPDeviceAddEdit3d media) {
    this.media = media;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ModelsMusicOnHold getMusicOnHold() {
    return musicOnHold;
  }
  public void setMusicOnHold(ModelsMusicOnHold musicOnHold) {
    this.musicOnHold = musicOnHold;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   * json omitempty is needed else voip fails on \"\" for owner_id
   **/
  @ApiModelProperty(value = "json omitempty is needed else voip fails on \"\" for owner_id")
  public String getOwnerId() {
    return ownerId;
  }
  public void setOwnerId(String ownerId) {
    this.ownerId = ownerId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ServiceVOIPDeviceAddEditProvision getProvision() {
    return provision;
  }
  public void setProvision(ServiceVOIPDeviceAddEditProvision provision) {
    this.provision = provision;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public ServiceVOIPDeviceAddEdit3a getSip() {
    return sip;
  }
  public void setSip(ServiceVOIPDeviceAddEdit3a sip) {
    this.sip = sip;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceVOIPDeviceAddEdit2 serviceVOIPDeviceAddEdit2 = (ServiceVOIPDeviceAddEdit2) o;
    return (this.callForward == null ? serviceVOIPDeviceAddEdit2.callForward == null : this.callForward.equals(serviceVOIPDeviceAddEdit2.callForward)) &&
        (this.callerId == null ? serviceVOIPDeviceAddEdit2.callerId == null : this.callerId.equals(serviceVOIPDeviceAddEdit2.callerId)) &&
        (this.deviceType == null ? serviceVOIPDeviceAddEdit2.deviceType == null : this.deviceType.equals(serviceVOIPDeviceAddEdit2.deviceType)) &&
        (this.doNotDisturb == null ? serviceVOIPDeviceAddEdit2.doNotDisturb == null : this.doNotDisturb.equals(serviceVOIPDeviceAddEdit2.doNotDisturb)) &&
        (this.enabled == null ? serviceVOIPDeviceAddEdit2.enabled == null : this.enabled.equals(serviceVOIPDeviceAddEdit2.enabled)) &&
        (this.macAddress == null ? serviceVOIPDeviceAddEdit2.macAddress == null : this.macAddress.equals(serviceVOIPDeviceAddEdit2.macAddress)) &&
        (this.media == null ? serviceVOIPDeviceAddEdit2.media == null : this.media.equals(serviceVOIPDeviceAddEdit2.media)) &&
        (this.musicOnHold == null ? serviceVOIPDeviceAddEdit2.musicOnHold == null : this.musicOnHold.equals(serviceVOIPDeviceAddEdit2.musicOnHold)) &&
        (this.name == null ? serviceVOIPDeviceAddEdit2.name == null : this.name.equals(serviceVOIPDeviceAddEdit2.name)) &&
        (this.ownerId == null ? serviceVOIPDeviceAddEdit2.ownerId == null : this.ownerId.equals(serviceVOIPDeviceAddEdit2.ownerId)) &&
        (this.provision == null ? serviceVOIPDeviceAddEdit2.provision == null : this.provision.equals(serviceVOIPDeviceAddEdit2.provision)) &&
        (this.sip == null ? serviceVOIPDeviceAddEdit2.sip == null : this.sip.equals(serviceVOIPDeviceAddEdit2.sip));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.callForward == null ? 0: this.callForward.hashCode());
    result = 31 * result + (this.callerId == null ? 0: this.callerId.hashCode());
    result = 31 * result + (this.deviceType == null ? 0: this.deviceType.hashCode());
    result = 31 * result + (this.doNotDisturb == null ? 0: this.doNotDisturb.hashCode());
    result = 31 * result + (this.enabled == null ? 0: this.enabled.hashCode());
    result = 31 * result + (this.macAddress == null ? 0: this.macAddress.hashCode());
    result = 31 * result + (this.media == null ? 0: this.media.hashCode());
    result = 31 * result + (this.musicOnHold == null ? 0: this.musicOnHold.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.ownerId == null ? 0: this.ownerId.hashCode());
    result = 31 * result + (this.provision == null ? 0: this.provision.hashCode());
    result = 31 * result + (this.sip == null ? 0: this.sip.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceVOIPDeviceAddEdit2 {\n");
    
    sb.append("  callForward: ").append(callForward).append("\n");
    sb.append("  callerId: ").append(callerId).append("\n");
    sb.append("  deviceType: ").append(deviceType).append("\n");
    sb.append("  doNotDisturb: ").append(doNotDisturb).append("\n");
    sb.append("  enabled: ").append(enabled).append("\n");
    sb.append("  macAddress: ").append(macAddress).append("\n");
    sb.append("  media: ").append(media).append("\n");
    sb.append("  musicOnHold: ").append(musicOnHold).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  ownerId: ").append(ownerId).append("\n");
    sb.append("  provision: ").append(provision).append("\n");
    sb.append("  sip: ").append(sip).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
