/**
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import org.openapitools.client.model.ServiceCallQueueStatusStats;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ServiceCallQueueStatusOutput {
  
  @SerializedName("active_recipient_count")
  private Integer activeRecipientCount = null;
  @SerializedName("available_recipient_count")
  private Integer availableRecipientCount = null;
  @SerializedName("node")
  private String node = null;
  @SerializedName("stats")
  private ServiceCallQueueStatusStats stats = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getActiveRecipientCount() {
    return activeRecipientCount;
  }
  public void setActiveRecipientCount(Integer activeRecipientCount) {
    this.activeRecipientCount = activeRecipientCount;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getAvailableRecipientCount() {
    return availableRecipientCount;
  }
  public void setAvailableRecipientCount(Integer availableRecipientCount) {
    this.availableRecipientCount = availableRecipientCount;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getNode() {
    return node;
  }
  public void setNode(String node) {
    this.node = node;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ServiceCallQueueStatusStats getStats() {
    return stats;
  }
  public void setStats(ServiceCallQueueStatusStats stats) {
    this.stats = stats;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceCallQueueStatusOutput serviceCallQueueStatusOutput = (ServiceCallQueueStatusOutput) o;
    return (this.activeRecipientCount == null ? serviceCallQueueStatusOutput.activeRecipientCount == null : this.activeRecipientCount.equals(serviceCallQueueStatusOutput.activeRecipientCount)) &&
        (this.availableRecipientCount == null ? serviceCallQueueStatusOutput.availableRecipientCount == null : this.availableRecipientCount.equals(serviceCallQueueStatusOutput.availableRecipientCount)) &&
        (this.node == null ? serviceCallQueueStatusOutput.node == null : this.node.equals(serviceCallQueueStatusOutput.node)) &&
        (this.stats == null ? serviceCallQueueStatusOutput.stats == null : this.stats.equals(serviceCallQueueStatusOutput.stats));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.activeRecipientCount == null ? 0: this.activeRecipientCount.hashCode());
    result = 31 * result + (this.availableRecipientCount == null ? 0: this.availableRecipientCount.hashCode());
    result = 31 * result + (this.node == null ? 0: this.node.hashCode());
    result = 31 * result + (this.stats == null ? 0: this.stats.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceCallQueueStatusOutput {\n");
    
    sb.append("  activeRecipientCount: ").append(activeRecipientCount).append("\n");
    sb.append("  availableRecipientCount: ").append(availableRecipientCount).append("\n");
    sb.append("  node: ").append(node).append("\n");
    sb.append("  stats: ").append(stats).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
