/**
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.ModelsVOIPSharedDoNotDisturb;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ServiceDeviceOutputShort {
  
  @SerializedName("device_type")
  private String deviceType = null;
  @SerializedName("do_not_disturb")
  private ModelsVOIPSharedDoNotDisturb doNotDisturb = null;
  @SerializedName("enabled")
  private Boolean enabled = null;
  @SerializedName("features")
  private List<String> features = null;
  @SerializedName("flags")
  private List<String> flags = null;
  @SerializedName("id")
  private String id = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("owner_id")
  private String ownerId = null;
  @SerializedName("username")
  private String username = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDeviceType() {
    return deviceType;
  }
  public void setDeviceType(String deviceType) {
    this.deviceType = deviceType;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ModelsVOIPSharedDoNotDisturb getDoNotDisturb() {
    return doNotDisturb;
  }
  public void setDoNotDisturb(ModelsVOIPSharedDoNotDisturb doNotDisturb) {
    this.doNotDisturb = doNotDisturb;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getEnabled() {
    return enabled;
  }
  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<String> getFeatures() {
    return features;
  }
  public void setFeatures(List<String> features) {
    this.features = features;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<String> getFlags() {
    return flags;
  }
  public void setFlags(List<String> flags) {
    this.flags = flags;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getOwnerId() {
    return ownerId;
  }
  public void setOwnerId(String ownerId) {
    this.ownerId = ownerId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUsername() {
    return username;
  }
  public void setUsername(String username) {
    this.username = username;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceDeviceOutputShort serviceDeviceOutputShort = (ServiceDeviceOutputShort) o;
    return (this.deviceType == null ? serviceDeviceOutputShort.deviceType == null : this.deviceType.equals(serviceDeviceOutputShort.deviceType)) &&
        (this.doNotDisturb == null ? serviceDeviceOutputShort.doNotDisturb == null : this.doNotDisturb.equals(serviceDeviceOutputShort.doNotDisturb)) &&
        (this.enabled == null ? serviceDeviceOutputShort.enabled == null : this.enabled.equals(serviceDeviceOutputShort.enabled)) &&
        (this.features == null ? serviceDeviceOutputShort.features == null : this.features.equals(serviceDeviceOutputShort.features)) &&
        (this.flags == null ? serviceDeviceOutputShort.flags == null : this.flags.equals(serviceDeviceOutputShort.flags)) &&
        (this.id == null ? serviceDeviceOutputShort.id == null : this.id.equals(serviceDeviceOutputShort.id)) &&
        (this.name == null ? serviceDeviceOutputShort.name == null : this.name.equals(serviceDeviceOutputShort.name)) &&
        (this.ownerId == null ? serviceDeviceOutputShort.ownerId == null : this.ownerId.equals(serviceDeviceOutputShort.ownerId)) &&
        (this.username == null ? serviceDeviceOutputShort.username == null : this.username.equals(serviceDeviceOutputShort.username));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.deviceType == null ? 0: this.deviceType.hashCode());
    result = 31 * result + (this.doNotDisturb == null ? 0: this.doNotDisturb.hashCode());
    result = 31 * result + (this.enabled == null ? 0: this.enabled.hashCode());
    result = 31 * result + (this.features == null ? 0: this.features.hashCode());
    result = 31 * result + (this.flags == null ? 0: this.flags.hashCode());
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.ownerId == null ? 0: this.ownerId.hashCode());
    result = 31 * result + (this.username == null ? 0: this.username.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceDeviceOutputShort {\n");
    
    sb.append("  deviceType: ").append(deviceType).append("\n");
    sb.append("  doNotDisturb: ").append(doNotDisturb).append("\n");
    sb.append("  enabled: ").append(enabled).append("\n");
    sb.append("  features: ").append(features).append("\n");
    sb.append("  flags: ").append(flags).append("\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  ownerId: ").append(ownerId).append("\n");
    sb.append("  username: ").append(username).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
