/**
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.Map;
import org.openapitools.client.model.OasAnyTypeNotMapped;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ServiceVOIPChannelRunMetaflowData {
  
  @SerializedName("children")
  private Map<String, ServiceVOIPChannelRunMetaflowData> children = null;
  @SerializedName("data")
  private Map<String, OasAnyTypeNotMapped> data = null;
  public enum ModuleEnum {
     transfer,  hold, 
  };
  @SerializedName("module")
  private ModuleEnum module = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Map<String, ServiceVOIPChannelRunMetaflowData> getChildren() {
    return children;
  }
  public void setChildren(Map<String, ServiceVOIPChannelRunMetaflowData> children) {
    this.children = children;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Map<String, OasAnyTypeNotMapped> getData() {
    return data;
  }
  public void setData(Map<String, OasAnyTypeNotMapped> data) {
    this.data = data;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public ModuleEnum getModule() {
    return module;
  }
  public void setModule(ModuleEnum module) {
    this.module = module;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceVOIPChannelRunMetaflowData serviceVOIPChannelRunMetaflowData = (ServiceVOIPChannelRunMetaflowData) o;
    return (this.children == null ? serviceVOIPChannelRunMetaflowData.children == null : this.children.equals(serviceVOIPChannelRunMetaflowData.children)) &&
        (this.data == null ? serviceVOIPChannelRunMetaflowData.data == null : this.data.equals(serviceVOIPChannelRunMetaflowData.data)) &&
        (this.module == null ? serviceVOIPChannelRunMetaflowData.module == null : this.module.equals(serviceVOIPChannelRunMetaflowData.module));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.children == null ? 0: this.children.hashCode());
    result = 31 * result + (this.data == null ? 0: this.data.hashCode());
    result = 31 * result + (this.module == null ? 0: this.module.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceVOIPChannelRunMetaflowData {\n");
    
    sb.append("  children: ").append(children).append("\n");
    sb.append("  data: ").append(data).append("\n");
    sb.append("  module: ").append(module).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
