/**
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ServiceAccountOutputShort {
  
  @SerializedName("descendants_count")
  private Integer descendantsCount = null;
  @SerializedName("flags")
  private List<String> flags = null;
  @SerializedName("id")
  private String id = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("realm")
  private String realm = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getDescendantsCount() {
    return descendantsCount;
  }
  public void setDescendantsCount(Integer descendantsCount) {
    this.descendantsCount = descendantsCount;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<String> getFlags() {
    return flags;
  }
  public void setFlags(List<String> flags) {
    this.flags = flags;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getRealm() {
    return realm;
  }
  public void setRealm(String realm) {
    this.realm = realm;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceAccountOutputShort serviceAccountOutputShort = (ServiceAccountOutputShort) o;
    return (this.descendantsCount == null ? serviceAccountOutputShort.descendantsCount == null : this.descendantsCount.equals(serviceAccountOutputShort.descendantsCount)) &&
        (this.flags == null ? serviceAccountOutputShort.flags == null : this.flags.equals(serviceAccountOutputShort.flags)) &&
        (this.id == null ? serviceAccountOutputShort.id == null : this.id.equals(serviceAccountOutputShort.id)) &&
        (this.name == null ? serviceAccountOutputShort.name == null : this.name.equals(serviceAccountOutputShort.name)) &&
        (this.realm == null ? serviceAccountOutputShort.realm == null : this.realm.equals(serviceAccountOutputShort.realm));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.descendantsCount == null ? 0: this.descendantsCount.hashCode());
    result = 31 * result + (this.flags == null ? 0: this.flags.hashCode());
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.realm == null ? 0: this.realm.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceAccountOutputShort {\n");
    
    sb.append("  descendantsCount: ").append(descendantsCount).append("\n");
    sb.append("  flags: ").append(flags).append("\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  realm: ").append(realm).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
