/**
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ServiceVOIPCallQueueRecipientLoginLogoutData {
  
  public enum ActionEnum {
     login,  logout, 
  };
  @SerializedName("action")
  private ActionEnum action = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public ActionEnum getAction() {
    return action;
  }
  public void setAction(ActionEnum action) {
    this.action = action;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceVOIPCallQueueRecipientLoginLogoutData serviceVOIPCallQueueRecipientLoginLogoutData = (ServiceVOIPCallQueueRecipientLoginLogoutData) o;
    return (this.action == null ? serviceVOIPCallQueueRecipientLoginLogoutData.action == null : this.action.equals(serviceVOIPCallQueueRecipientLoginLogoutData.action));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.action == null ? 0: this.action.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceVOIPCallQueueRecipientLoginLogoutData {\n");
    
    sb.append("  action: ").append(action).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
