/**
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ServiceImpersonatedUserInfo {
  
  @SerializedName("email")
  private String email = null;
  @SerializedName("first_name")
  private String firstName = null;
  @SerializedName("full_name")
  private String fullName = null;
  @SerializedName("has_avatar")
  private Boolean hasAvatar = null;
  @SerializedName("last_name")
  private String lastName = null;
  @SerializedName("priv_level")
  private String privLevel = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getEmail() {
    return email;
  }
  public void setEmail(String email) {
    this.email = email;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getFirstName() {
    return firstName;
  }
  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getFullName() {
    return fullName;
  }
  public void setFullName(String fullName) {
    this.fullName = fullName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getHasAvatar() {
    return hasAvatar;
  }
  public void setHasAvatar(Boolean hasAvatar) {
    this.hasAvatar = hasAvatar;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLastName() {
    return lastName;
  }
  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPrivLevel() {
    return privLevel;
  }
  public void setPrivLevel(String privLevel) {
    this.privLevel = privLevel;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceImpersonatedUserInfo serviceImpersonatedUserInfo = (ServiceImpersonatedUserInfo) o;
    return (this.email == null ? serviceImpersonatedUserInfo.email == null : this.email.equals(serviceImpersonatedUserInfo.email)) &&
        (this.firstName == null ? serviceImpersonatedUserInfo.firstName == null : this.firstName.equals(serviceImpersonatedUserInfo.firstName)) &&
        (this.fullName == null ? serviceImpersonatedUserInfo.fullName == null : this.fullName.equals(serviceImpersonatedUserInfo.fullName)) &&
        (this.hasAvatar == null ? serviceImpersonatedUserInfo.hasAvatar == null : this.hasAvatar.equals(serviceImpersonatedUserInfo.hasAvatar)) &&
        (this.lastName == null ? serviceImpersonatedUserInfo.lastName == null : this.lastName.equals(serviceImpersonatedUserInfo.lastName)) &&
        (this.privLevel == null ? serviceImpersonatedUserInfo.privLevel == null : this.privLevel.equals(serviceImpersonatedUserInfo.privLevel));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.email == null ? 0: this.email.hashCode());
    result = 31 * result + (this.firstName == null ? 0: this.firstName.hashCode());
    result = 31 * result + (this.fullName == null ? 0: this.fullName.hashCode());
    result = 31 * result + (this.hasAvatar == null ? 0: this.hasAvatar.hashCode());
    result = 31 * result + (this.lastName == null ? 0: this.lastName.hashCode());
    result = 31 * result + (this.privLevel == null ? 0: this.privLevel.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceImpersonatedUserInfo {\n");
    
    sb.append("  email: ").append(email).append("\n");
    sb.append("  firstName: ").append(firstName).append("\n");
    sb.append("  fullName: ").append(fullName).append("\n");
    sb.append("  hasAvatar: ").append(hasAvatar).append("\n");
    sb.append("  lastName: ").append(lastName).append("\n");
    sb.append("  privLevel: ").append(privLevel).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
