/**
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ServiceVOIPTemporalRuleAddEdit2 {
  
  public enum CycleEnum {
     date,  daily,  weekly,  monthly,  yearly, 
  };
  @SerializedName("cycle")
  private CycleEnum cycle = null;
  @SerializedName("days")
  private List<Integer> days = null;
  @SerializedName("enabled")
  private Boolean enabled = null;
  @SerializedName("interval")
  private Integer interval = null;
  @SerializedName("month")
  private Integer month = null;
  @SerializedName("name")
  private String name = null;
  public enum OrdinalEnum {
     every,  first,  second,  third,  fourth,  fifth,  last, 
  };
  @SerializedName("ordinal")
  private OrdinalEnum ordinal = null;
  @SerializedName("start_date")
  private Integer startDate = null;
  @SerializedName("start_date_req")
  private String startDateReq = null;
  @SerializedName("time_window_start")
  private Integer timeWindowStart = null;
  @SerializedName("time_window_start_req")
  private String timeWindowStartReq = null;
  @SerializedName("time_window_stop")
  private Integer timeWindowStop = null;
  @SerializedName("time_window_stop_req")
  private String timeWindowStopReq = null;
  @SerializedName("wdays")
  private List<String> wdays = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public CycleEnum getCycle() {
    return cycle;
  }
  public void setCycle(CycleEnum cycle) {
    this.cycle = cycle;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Integer> getDays() {
    return days;
  }
  public void setDays(List<Integer> days) {
    this.days = days;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getEnabled() {
    return enabled;
  }
  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }

  /**
   * minimum: 1
   **/
  @ApiModelProperty(value = "")
  public Integer getInterval() {
    return interval;
  }
  public void setInterval(Integer interval) {
    this.interval = interval;
  }

  /**
   * minimum: 1
   * maximum: 12
   **/
  @ApiModelProperty(value = "")
  public Integer getMonth() {
    return month;
  }
  public void setMonth(Integer month) {
    this.month = month;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public OrdinalEnum getOrdinal() {
    return ordinal;
  }
  public void setOrdinal(OrdinalEnum ordinal) {
    this.ordinal = ordinal;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getStartDate() {
    return startDate;
  }
  public void setStartDate(Integer startDate) {
    this.startDate = startDate;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getStartDateReq() {
    return startDateReq;
  }
  public void setStartDateReq(String startDateReq) {
    this.startDateReq = startDateReq;
  }

  /**
   * minimum: 0
   * maximum: 86400
   **/
  @ApiModelProperty(value = "")
  public Integer getTimeWindowStart() {
    return timeWindowStart;
  }
  public void setTimeWindowStart(Integer timeWindowStart) {
    this.timeWindowStart = timeWindowStart;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getTimeWindowStartReq() {
    return timeWindowStartReq;
  }
  public void setTimeWindowStartReq(String timeWindowStartReq) {
    this.timeWindowStartReq = timeWindowStartReq;
  }

  /**
   * minimum: 0
   * maximum: 86400
   **/
  @ApiModelProperty(value = "")
  public Integer getTimeWindowStop() {
    return timeWindowStop;
  }
  public void setTimeWindowStop(Integer timeWindowStop) {
    this.timeWindowStop = timeWindowStop;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getTimeWindowStopReq() {
    return timeWindowStopReq;
  }
  public void setTimeWindowStopReq(String timeWindowStopReq) {
    this.timeWindowStopReq = timeWindowStopReq;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<String> getWdays() {
    return wdays;
  }
  public void setWdays(List<String> wdays) {
    this.wdays = wdays;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceVOIPTemporalRuleAddEdit2 serviceVOIPTemporalRuleAddEdit2 = (ServiceVOIPTemporalRuleAddEdit2) o;
    return (this.cycle == null ? serviceVOIPTemporalRuleAddEdit2.cycle == null : this.cycle.equals(serviceVOIPTemporalRuleAddEdit2.cycle)) &&
        (this.days == null ? serviceVOIPTemporalRuleAddEdit2.days == null : this.days.equals(serviceVOIPTemporalRuleAddEdit2.days)) &&
        (this.enabled == null ? serviceVOIPTemporalRuleAddEdit2.enabled == null : this.enabled.equals(serviceVOIPTemporalRuleAddEdit2.enabled)) &&
        (this.interval == null ? serviceVOIPTemporalRuleAddEdit2.interval == null : this.interval.equals(serviceVOIPTemporalRuleAddEdit2.interval)) &&
        (this.month == null ? serviceVOIPTemporalRuleAddEdit2.month == null : this.month.equals(serviceVOIPTemporalRuleAddEdit2.month)) &&
        (this.name == null ? serviceVOIPTemporalRuleAddEdit2.name == null : this.name.equals(serviceVOIPTemporalRuleAddEdit2.name)) &&
        (this.ordinal == null ? serviceVOIPTemporalRuleAddEdit2.ordinal == null : this.ordinal.equals(serviceVOIPTemporalRuleAddEdit2.ordinal)) &&
        (this.startDate == null ? serviceVOIPTemporalRuleAddEdit2.startDate == null : this.startDate.equals(serviceVOIPTemporalRuleAddEdit2.startDate)) &&
        (this.startDateReq == null ? serviceVOIPTemporalRuleAddEdit2.startDateReq == null : this.startDateReq.equals(serviceVOIPTemporalRuleAddEdit2.startDateReq)) &&
        (this.timeWindowStart == null ? serviceVOIPTemporalRuleAddEdit2.timeWindowStart == null : this.timeWindowStart.equals(serviceVOIPTemporalRuleAddEdit2.timeWindowStart)) &&
        (this.timeWindowStartReq == null ? serviceVOIPTemporalRuleAddEdit2.timeWindowStartReq == null : this.timeWindowStartReq.equals(serviceVOIPTemporalRuleAddEdit2.timeWindowStartReq)) &&
        (this.timeWindowStop == null ? serviceVOIPTemporalRuleAddEdit2.timeWindowStop == null : this.timeWindowStop.equals(serviceVOIPTemporalRuleAddEdit2.timeWindowStop)) &&
        (this.timeWindowStopReq == null ? serviceVOIPTemporalRuleAddEdit2.timeWindowStopReq == null : this.timeWindowStopReq.equals(serviceVOIPTemporalRuleAddEdit2.timeWindowStopReq)) &&
        (this.wdays == null ? serviceVOIPTemporalRuleAddEdit2.wdays == null : this.wdays.equals(serviceVOIPTemporalRuleAddEdit2.wdays));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.cycle == null ? 0: this.cycle.hashCode());
    result = 31 * result + (this.days == null ? 0: this.days.hashCode());
    result = 31 * result + (this.enabled == null ? 0: this.enabled.hashCode());
    result = 31 * result + (this.interval == null ? 0: this.interval.hashCode());
    result = 31 * result + (this.month == null ? 0: this.month.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.ordinal == null ? 0: this.ordinal.hashCode());
    result = 31 * result + (this.startDate == null ? 0: this.startDate.hashCode());
    result = 31 * result + (this.startDateReq == null ? 0: this.startDateReq.hashCode());
    result = 31 * result + (this.timeWindowStart == null ? 0: this.timeWindowStart.hashCode());
    result = 31 * result + (this.timeWindowStartReq == null ? 0: this.timeWindowStartReq.hashCode());
    result = 31 * result + (this.timeWindowStop == null ? 0: this.timeWindowStop.hashCode());
    result = 31 * result + (this.timeWindowStopReq == null ? 0: this.timeWindowStopReq.hashCode());
    result = 31 * result + (this.wdays == null ? 0: this.wdays.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceVOIPTemporalRuleAddEdit2 {\n");
    
    sb.append("  cycle: ").append(cycle).append("\n");
    sb.append("  days: ").append(days).append("\n");
    sb.append("  enabled: ").append(enabled).append("\n");
    sb.append("  interval: ").append(interval).append("\n");
    sb.append("  month: ").append(month).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  ordinal: ").append(ordinal).append("\n");
    sb.append("  startDate: ").append(startDate).append("\n");
    sb.append("  startDateReq: ").append(startDateReq).append("\n");
    sb.append("  timeWindowStart: ").append(timeWindowStart).append("\n");
    sb.append("  timeWindowStartReq: ").append(timeWindowStartReq).append("\n");
    sb.append("  timeWindowStop: ").append(timeWindowStop).append("\n");
    sb.append("  timeWindowStopReq: ").append(timeWindowStopReq).append("\n");
    sb.append("  wdays: ").append(wdays).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
